import type { Qcm } from "../types";
import { annale } from "./helpers";

/**
 * Annales officielles — thème « Droits et devoirs »
 * (pages 5-6 du document ministériel).
 */
export const annalesDroits: Qcm[] = [
  annale(
    "an-dd-001",
    "p3-s1",
    5,
    "À quoi sert le droit de grève ?",
    "À cesser le travail pour défendre des revendications professionnelles",
    ["À prendre des congés supplémentaires", "À changer d'employeur", "À refuser de payer ses impôts"],
    "Le droit de grève permet aux salariés de cesser collectivement le travail pour défendre leurs intérêts.",
  ),
  annale(
    "an-dd-002",
    "p3-s1",
    5,
    "Au nom de quoi l'État justifie-t-il la restriction des droits ?",
    "De l'ordre public et de la sécurité",
    ["Des convictions du gouvernement", "De la tradition", "Des intérêts économiques privés"],
    "Les libertés peuvent être limitées par la loi pour protéger l'ordre public et les droits d'autrui.",
  ),
  annale(
    "an-dd-003",
    "p3-s1",
    5,
    "Laquelle de ces citations est inscrite dans la Déclaration des Droits de l'Homme et du Citoyen de 1789 ?",
    "« Les hommes naissent et demeurent libres et égaux en droits »",
    [
      "« La propriété, c'est le vol »",
      "« L'État, c'est moi »",
      "« Un pour tous, tous pour un »",
    ],
    "C'est l'article 1er de la DDHC du 26 août 1789.",
  ),
  annale(
    "an-dd-004",
    "p3-s1",
    5,
    "L'article 4 de la Déclaration des droits de l'homme et du citoyen affirme que « la liberté consiste à pouvoir faire tout ce qui ne nuit pas à autrui ». Qu'est-ce que cela signifie ?",
    "Ma liberté s'arrête là où commence celle des autres",
    [
      "Chacun peut faire tout ce qu'il veut",
      "La liberté n'existe que chez soi",
      "Seul l'État décide de ce qui est permis",
    ],
    "La liberté de chacun est limitée par le respect des droits et libertés d'autrui.",
  ),
  annale(
    "an-dd-005",
    "p3-s1",
    5,
    "Que dit l'article 1er de la Constitution française ?",
    "La France est une République indivisible, laïque, démocratique et sociale",
    [
      "La France est une monarchie parlementaire",
      "La France est un État fédéral",
      "Le français est la seule langue autorisée",
    ],
    "L'article 1er affirme aussi l'égalité devant la loi sans distinction d'origine, de race ou de religion.",
  ),
  annale(
    "an-dd-006",
    "p3-s1",
    5,
    "Que garantit la liberté de la presse ?",
    "Le droit d'informer et de publier sans censure",
    ["Le droit de diffamer", "L'obligation d'acheter des journaux", "Le contrôle de l'État sur les médias"],
    "La presse est libre : elle informe sans censure préalable, dans le respect de la loi (diffamation interdite).",
  ),
  annale(
    "an-dd-007",
    "p3-s1",
    5,
    "Que permet la liberté de circulation ?",
    "Se déplacer librement sur le territoire, en sortir et y revenir",
    ["Voyager gratuitement en train", "Conduire sans permis", "S'installer dans un logement vide"],
    "Chacun peut circuler librement en France et quitter le territoire, dans le respect de la loi.",
  ),
  annale(
    "an-dd-008",
    "p3-s1",
    5,
    "Que signifie être citoyen d'un État ?",
    "Avoir sa nationalité, avec les droits et devoirs qui s'y attachent",
    ["Habiter simplement sur son territoire", "Y payer des impôts", "Y être né obligatoirement"],
    "La citoyenneté lie une personne à un État : droits (vote…) et devoirs (respect des lois…).",
  ),
  annale(
    "an-dd-009",
    "p3-s1",
    5,
    "Que sont les droits fondamentaux ?",
    "Des droits essentiels garantis à toute personne",
    [
      "Des privilèges accordés aux élus",
      "Des droits réservés aux Français",
      "Des règles de politesse",
    ],
    "Les droits fondamentaux (liberté, égalité, sûreté…) sont garantis par la Constitution et les traités.",
  ),
  annale(
    "an-dd-010",
    "p3-s1",
    5,
    "Quel droit protège une personne contre une arrestation arbitraire ?",
    "Le droit à la sûreté",
    ["Le droit de propriété", "Le droit de grève", "Le droit au logement"],
    "La sûreté protège chacun contre les arrestations et détentions arbitraires (article 7 de la DDHC).",
  ),
  annale(
    "an-dd-011",
    "p3-s1",
    5,
    "Quel est le texte fondateur établissant les droits et les devoirs de chaque citoyen ?",
    "La Déclaration des droits de l'homme et du citoyen de 1789",
    ["Le Code de la route", "Le traité de Rome", "L'édit de Nantes"],
    "La DDHC de 1789 fonde les droits et devoirs des citoyens ; elle a valeur constitutionnelle.",
  ),
  annale(
    "an-dd-012",
    "p3-s1",
    5,
    "Quel texte affirme que tous les hommes naissent libres et égaux en droits ?",
    "La Déclaration des droits de l'homme et du citoyen",
    ["Le Code civil", "La Charte de l'environnement", "Le traité de Maastricht"],
    "L'article 1er de la DDHC de 1789 proclame la liberté et l'égalité en droits.",
  ),
  annale(
    "an-dd-013",
    "p3-s1",
    5,
    "Quelle situation est une atteinte à la dignité humaine ?",
    "La traite des êtres humains",
    ["Un contrôle d'identité", "Le paiement d'une amende", "Un refus de crédit bancaire"],
    "L'esclavage, la traite et les traitements inhumains ou dégradants portent atteinte à la dignité humaine.",
  ),
  annale(
    "an-dd-014",
    "p3-s1",
    5,
    "Qu'est-ce que la liberté d'expression ?",
    "Le droit d'exprimer ses opinions dans les limites fixées par la loi",
    [
      "Le droit de dire absolument tout, sans limite",
      "Un droit réservé aux journalistes",
      "Le droit de voter",
    ],
    "Chacun peut exprimer ses opinions ; l'injure, la diffamation et l'appel à la haine restent punis.",
  ),
  annale(
    "an-dd-015",
    "p3-s1",
    5,
    "Suite à une interpellation par la police, il est possible de :",
    "Être assisté par un avocat",
    ["Être détenu sans limite de temps", "Être jugé immédiatement sur place", "Être privé de nourriture"],
    "Toute personne interpellée a des droits : avocat, information sur les faits reprochés, examen médical…",
  ),
  annale(
    "an-dd-016",
    "p3-s1",
    5,
    "Tous les citoyens français ont-ils une religion ?",
    "Non, chacun est libre de croire ou de ne pas croire",
    ["Oui, c'est obligatoire", "Oui, elle est inscrite sur la carte d'identité", "Non, la religion est interdite"],
    "La liberté de conscience garantit le droit d'avoir une religion, d'en changer ou de ne pas en avoir.",
  ),
  annale(
    "an-dd-017",
    "p3-s2",
    5,
    "À quel âge est la majorité numérique en France ?",
    "15 ans",
    ["13 ans", "16 ans", "18 ans"],
    "À partir de 15 ans, un mineur peut consentir seul au traitement de ses données (réseaux sociaux).",
  ),
  annale(
    "an-dd-018",
    "p3-s2",
    5,
    "Dans lequel de ces endroits est-on autorisé à fumer ?",
    "Dans la rue",
    ["Dans un restaurant", "Dans les transports en commun", "Dans un hôpital"],
    "Fumer est interdit dans les lieux publics fermés (transports, restaurants, hôpitaux…).",
  ),
  annale(
    "an-dd-019",
    "p3-s2",
    5,
    "En France, la conduite sans permis d'une moto est :",
    "Un délit puni par la loi",
    ["Autorisée en ville", "Tolérée pour les petits trajets", "Autorisée le week-end"],
    "Conduire sans permis est un délit passible d'amende, voire de prison.",
  ),
  annale(
    "an-dd-020",
    "p3-s2",
    5,
    "En quoi consiste le devoir de solidarité ?",
    "Contribuer à aider les personnes en difficulté, notamment par l'impôt",
    ["Donner tout son salaire", "Héberger des inconnus", "Adhérer à une association obligatoirement"],
    "La solidarité passe par la protection sociale, financée par les impôts et cotisations, et par l'entraide.",
  ),
  annale(
    "an-dd-021",
    "p3-s2",
    5,
    "Est-ce légal d'être marié à plusieurs personnes en même temps ?",
    "Non, la polygamie est interdite en France",
    ["Oui, avec l'accord des conjoints", "Oui, pour les étrangers", "Oui, après 10 ans de mariage"],
    "La polygamie est interdite : on ne peut être marié qu'à une seule personne à la fois.",
  ),
  annale(
    "an-dd-022",
    "p3-s2",
    5,
    "Est-ce obligatoire de déclarer ses impôts chaque année en France ?",
    "Oui, c'est une obligation légale annuelle",
    ["Non, c'est facultatif", "Oui, tous les cinq ans", "Seulement pour les propriétaires"],
    "La déclaration de revenus est obligatoire chaque année pour tous les foyers fiscaux.",
  ),
  annale(
    "an-dd-023",
    "p3-s2",
    5,
    "Est-il obligatoire de porter secours à une personne en danger ?",
    "Oui, la non-assistance à personne en danger est punie",
    ["Non, c'est un choix moral", "Oui, uniquement pour les médecins", "Non, sauf pour la famille"],
    "Ne pas porter secours (ou ne pas alerter les secours) est un délit : la non-assistance à personne en danger.",
  ),
  annale(
    "an-dd-024",
    "p3-s2",
    5,
    "Être juré d'assises est :",
    "Un devoir civique auquel on ne peut se soustraire sans motif grave",
    ["Une mission volontaire rémunérée au SMIC", "Réservé aux magistrats", "Une simple option"],
    "Tout citoyen tiré au sort doit participer au jury d'assises, sauf dispense pour motif sérieux.",
  ),
  annale(
    "an-dd-025",
    "p3-s2",
    5,
    "La vente d'alcool en France est interdite aux personnes de moins de :",
    "18 ans",
    ["16 ans", "21 ans", "15 ans"],
    "La vente d'alcool aux mineurs (moins de 18 ans) est interdite.",
  ),
  annale(
    "an-dd-026",
    "p3-s2",
    5,
    "Le non-respect du code de la route est :",
    "Une infraction punie par la loi",
    ["Une simple incivilité sans sanction", "Toléré la nuit", "Puni uniquement en cas d'accident"],
    "Les infractions routières sont sanctionnées : amendes, retrait de points, suspension du permis…",
  ),
  annale(
    "an-dd-027",
    "p3-s2",
    5,
    "Lequel de ces crimes ou délits peut entrainer la privation des droits civils et politiques par un juge ?",
    "La fraude électorale",
    ["Un excès de vitesse", "Un stationnement gênant", "Un retard de paiement"],
    "Pour des faits graves (fraude électorale, corruption…), le juge peut priver une personne de ses droits civiques.",
  ),
  annale(
    "an-dd-028",
    "p3-s2",
    5,
    "Pour obtenir une carte d'identité, il faut :",
    "Avoir la nationalité française et fournir les justificatifs demandés",
    ["Payer une taxe de 100 €", "Avoir plus de 18 ans", "Posséder un passeport"],
    "La carte nationale d'identité est gratuite et délivrée aux personnes de nationalité française, sans condition d'âge.",
  ),
  annale(
    "an-dd-029",
    "p3-s1",
    5,
    "Pour quel motif peut-on limiter la liberté d'expression ?",
    "L'injure, la diffamation ou l'incitation à la haine",
    ["La critique du gouvernement", "L'expression d'une opinion religieuse", "La satire et l'humour"],
    "La loi punit les abus de la liberté d'expression qui portent atteinte à autrui ou à l'ordre public.",
  ),
  annale(
    "an-dd-030",
    "p3-s2",
    6,
    "Que doit faire un citoyen s'il est appelé à être juré dans un procès d'assises ?",
    "Se présenter et participer au jury",
    ["Payer pour être remplacé", "Refuser par simple courrier", "Choisir un autre procès"],
    "Être juré est un devoir civique : il faut se présenter, sauf dispense accordée pour motif grave.",
  ),
  annale(
    "an-dd-031",
    "p3-s2",
    6,
    "Quel est l'âge de la majorité civile en France ?",
    "18 ans",
    ["16 ans", "21 ans", "20 ans"],
    "Depuis 1974, la majorité civile est fixée à 18 ans.",
  ),
  annale(
    "an-dd-032",
    "p3-s2",
    6,
    "Quel est l'un des devoirs principaux d'un citoyen français ?",
    "Respecter les lois",
    ["Adhérer à un parti politique", "Regarder les débats parlementaires", "Travailler dans la fonction publique"],
    "Respecter la loi, payer l'impôt et participer à la défense du pays sont des devoirs du citoyen.",
  ),
  annale(
    "an-dd-033",
    "p3-s2",
    6,
    "Quelle est l'infraction la plus grave ?",
    "Le crime",
    ["Le délit", "La contravention", "L'incivilité"],
    "Les infractions sont classées par gravité : contraventions, délits, crimes (jugés en cour d'assises).",
  ),
  annale(
    "an-dd-034",
    "p3-s2",
    6,
    "Qu'est-ce que la citoyenneté numérique ?",
    "Se comporter de façon responsable et respectueuse sur internet",
    [
      "Avoir une carte d'identité électronique",
      "Posséder un ordinateur",
      "Voter uniquement en ligne",
    ],
    "Les droits et devoirs du citoyen s'appliquent aussi en ligne : respect d'autrui, pas de haine ni de harcèlement.",
  ),
  annale(
    "an-dd-035",
    "p3-s2",
    6,
    "Qu'est-ce que le devoir de mémoire ?",
    "Se souvenir des événements douloureux de l'histoire pour qu'ils ne se reproduisent pas",
    [
      "Apprendre par cœur tous les rois de France",
      "Conserver ses papiers de famille",
      "Fêter tous les anniversaires officiels",
    ],
    "Le devoir de mémoire honore les victimes de l'histoire (Shoah, guerres, esclavage) et éclaire le présent.",
  ),
  annale(
    "an-dd-036",
    "p3-s2",
    6,
    "Qui peut être appelé à faire partie d'un jury d'assises en France ?",
    "Tout citoyen français de plus de 23 ans, tiré au sort sur les listes électorales",
    ["Uniquement les avocats", "Uniquement les fonctionnaires", "Les personnes volontaires de plus de 30 ans"],
    "Les jurés sont tirés au sort parmi les citoyens inscrits sur les listes électorales, âgés d'au moins 23 ans.",
  ),
  annale(
    "an-dd-037",
    "p3-s2",
    6,
    "Une personne est privée de ses droits civils et politiques pendant 5 ans suite à une condamnation. Parmi ces propositions laquelle est correcte ? Pendant 5 ans,…",
    "Elle ne peut ni voter ni être élue",
    ["Elle ne peut plus travailler", "Elle ne peut plus se marier", "Elle ne peut plus voyager"],
    "La privation des droits civiques suspend notamment le droit de vote et l'éligibilité.",
  ),
];
