import type { Qcm } from "../types";
import { annale } from "./helpers";

/**
 * Annales officielles — thème « Histoire, géographie et culture »
 * (pages 7-9 du document ministériel).
 */
export const annalesHistoire: Qcm[] = [
  annale(
    "an-hg-001",
    "p4-s1",
    7,
    "Parmi ces textes, lequel a été adopté sous Napoléon Ier ?",
    "Le Code civil",
    ["La Déclaration des droits de l'homme", "La loi de 1905", "La Constitution de 1958"],
    "Le Code civil, promulgué en 1804, est l'œuvre majeure de Napoléon Ier.",
  ),
  annale(
    "an-hg-002",
    "p4-s1",
    7,
    "Qui a été président de la Ve République ?",
    "Charles de Gaulle",
    ["Georges Clemenceau", "Napoléon III", "Jean Jaurès"],
    "Charles de Gaulle, fondateur de la Ve République en 1958, en fut le premier président.",
  ),
  annale(
    "an-hg-003",
    "p4-s1",
    7,
    "Quel est l'objectif des lois scolaires de la IIIe République ?",
    "Rendre l'école gratuite, laïque et obligatoire",
    ["Créer les universités", "Réserver l'école aux garçons", "Rendre l'école payante"],
    "Les lois Jules Ferry (1881-1882) instaurent l'école gratuite, laïque et obligatoire.",
  ),
  annale(
    "an-hg-004",
    "p4-s1",
    7,
    "Que signifie la date du 14 juillet pour les Français ?",
    "La prise de la Bastille en 1789",
    ["La fin de la Seconde Guerre mondiale", "Le couronnement de Napoléon", "L'abolition de l'esclavage"],
    "Le 14 juillet, fête nationale, commémore la prise de la Bastille (1789) et la fête de la Fédération (1790).",
  ),
  annale(
    "an-hg-005",
    "p4-s1",
    7,
    "Pourquoi l'année 1958 est importante pour la France ?",
    "C'est la naissance de la Ve République",
    ["C'est la fin de la Première Guerre mondiale", "C'est l'année de l'abolition de la peine de mort", "C'est l'entrée dans l'euro"],
    "En 1958, une nouvelle Constitution fonde la Ve République, notre régime actuel.",
  ),
  annale(
    "an-hg-006",
    "p4-s1",
    7,
    "Lequel de ces pays est un pays fondateur de l'Union européenne ?",
    "L'Italie",
    ["L'Espagne", "La Pologne", "Le Royaume-Uni"],
    "Les six fondateurs : France, Allemagne, Italie, Belgique, Pays-Bas, Luxembourg.",
  ),
  annale(
    "an-hg-007",
    "p4-s1",
    7,
    "Simone Veil est une figure importante de l'histoire française. Elle a notamment :",
    "Fait voter la loi légalisant l'interruption volontaire de grossesse (1975)",
    ["Aboli la peine de mort", "Été présidente de la République", "Écrit la Constitution de 1958"],
    "Ministre de la Santé, Simone Veil a porté la loi de 1975 sur l'IVG ; elle fut aussi présidente du Parlement européen.",
  ),
  annale(
    "an-hg-008",
    "p4-s1",
    7,
    "Dans quelle région est située une partie des plages du débarquement ayant permis d'engager la libération de la France ?",
    "La Normandie",
    ["La Bretagne", "La Provence", "Les Hauts-de-France"],
    "Le débarquement allié du 6 juin 1944 a eu lieu sur les plages de Normandie.",
  ),
  annale(
    "an-hg-009",
    "p4-s1",
    7,
    "Dans quelle ville les rois de France étaient-ils couronnés ?",
    "Reims",
    ["Paris", "Versailles", "Orléans"],
    "Les rois de France étaient sacrés dans la cathédrale de Reims.",
  ),
  annale(
    "an-hg-010",
    "p4-s1",
    7,
    "Quel roi de France a été guillotiné pendant la Révolution française ?",
    "Louis XVI",
    ["Louis XIV", "Henri IV", "François Ier"],
    "Louis XVI a été guillotiné le 21 janvier 1793.",
  ),
  annale(
    "an-hg-011",
    "p4-s1",
    7,
    "En quelle année a débuté la Révolution française ?",
    "1789",
    ["1804", "1848", "1715"],
    "La Révolution française débute en 1789, avec notamment la prise de la Bastille le 14 juillet.",
  ),
  annale(
    "an-hg-012",
    "p4-s1",
    7,
    "En quelle année Napoléon Ier est-il devenu empereur ?",
    "1804",
    ["1789", "1815", "1830"],
    "Napoléon Bonaparte s'est fait sacrer empereur des Français en 1804.",
  ),
  annale(
    "an-hg-013",
    "p4-s1",
    7,
    "Lequel de ces personnages a un lien avec la République française ?",
    "Marianne",
    ["Astérix", "Jeanne Calment", "Le roi Arthur"],
    "Marianne incarne la République française et ses valeurs.",
  ),
  annale(
    "an-hg-014",
    "p4-s1",
    7,
    "De quand date l'appel à la résistance du général de Gaulle ?",
    "Du 18 juin 1940",
    ["Du 11 novembre 1918", "Du 8 mai 1945", "Du 14 juillet 1939"],
    "Depuis Londres, le général de Gaulle appelle à poursuivre le combat le 18 juin 1940.",
  ),
  annale(
    "an-hg-015",
    "p4-s1",
    7,
    "Qu'est-ce que la Shoah ?",
    "L'extermination des Juifs d'Europe par l'Allemagne nazie",
    ["Une bataille de la Première Guerre mondiale", "Un traité de paix", "Une région d'Europe centrale"],
    "La Shoah désigne le génocide de six millions de Juifs pendant la Seconde Guerre mondiale.",
  ),
  annale(
    "an-hg-016",
    "p4-s1",
    7,
    "Quel pays a été une colonie française ?",
    "L'Algérie",
    ["La Grèce", "L'Argentine", "La Norvège"],
    "L'Algérie a été colonie française de 1830 à son indépendance en 1962.",
  ),
  annale(
    "an-hg-017",
    "p4-s1",
    7,
    "Qui a rendu l'école gratuite, laïque et obligatoire ?",
    "Jules Ferry",
    ["Napoléon Ier", "Victor Hugo", "Charles de Gaulle"],
    "Les lois de Jules Ferry (1881-1882) fondent l'école publique gratuite, laïque et obligatoire.",
  ),
  annale(
    "an-hg-018",
    "p4-s1",
    7,
    "Depuis quand les Français élisent-ils le président de la République au suffrage universel direct ?",
    "Depuis 1962",
    ["Depuis 1789", "Depuis 1945", "Depuis 1981"],
    "Le référendum de 1962 instaure l'élection du président au suffrage universel direct (première élection en 1965).",
  ),
  annale(
    "an-hg-019",
    "p4-s1",
    7,
    "En quelle année l'Union européenne a-t-elle été fondée ?",
    "1992",
    ["1945", "1957", "2002"],
    "L'Union européenne est fondée par le traité de Maastricht, signé en 1992.",
  ),
  annale(
    "an-hg-020",
    "p4-s1",
    7,
    "Quand a eu lieu la Seconde Guerre mondiale ?",
    "De 1939 à 1945",
    ["De 1914 à 1918", "De 1929 à 1935", "De 1946 à 1954"],
    "La Seconde Guerre mondiale s'est déroulée de 1939 à 1945.",
  ),
  annale(
    "an-hg-021",
    "p4-s1",
    7,
    "Quand a eu lieu la Première Guerre mondiale ?",
    "De 1914 à 1918",
    ["De 1939 à 1945", "De 1870 à 1871", "De 1905 à 1910"],
    "La Première Guerre mondiale s'est déroulée de 1914 à 1918.",
  ),
  annale(
    "an-hg-022",
    "p4-s1",
    7,
    "Sous quel président a été abolie la peine de mort en France ?",
    "François Mitterrand",
    ["Charles de Gaulle", "Jacques Chirac", "Georges Pompidou"],
    "La peine de mort a été abolie en 1981, sous François Mitterrand, par la loi portée par Robert Badinter.",
  ),
  annale(
    "an-hg-023",
    "p4-s1",
    7,
    "Que célèbre-t-on le 8 mai ?",
    "La victoire des Alliés et la fin de la Seconde Guerre mondiale en Europe (1945)",
    ["L'armistice de 1918", "La prise de la Bastille", "La fête du Travail"],
    "Le 8 mai 1945 marque la capitulation de l'Allemagne nazie.",
  ),
  annale(
    "an-hg-024",
    "p4-s1",
    7,
    "Quelle est la première étape de la construction européenne en 1951 ?",
    "La Communauté européenne du charbon et de l'acier (CECA)",
    ["Le traité de Maastricht", "La création de l'euro", "L'espace Schengen"],
    "En 1951, six pays créent la CECA, première communauté européenne.",
  ),
  annale(
    "an-hg-025",
    "p4-s1",
    7,
    "Qui était une figure de la Résistance française pendant la Seconde Guerre mondiale ?",
    "Jean Moulin",
    ["Georges Clemenceau", "Jules Ferry", "Gustave Eiffel"],
    "Jean Moulin a unifié la Résistance intérieure ; il est mort sous la torture en 1943.",
  ),
  annale(
    "an-hg-026",
    "p4-s1",
    7,
    "Le 11 novembre est un jour férié. À quoi correspond cette date ?",
    "À l'armistice de la Première Guerre mondiale (1918)",
    ["À la fin de la Seconde Guerre mondiale", "À la fête nationale", "À la journée de l'Europe"],
    "Le 11 novembre 1918, l'armistice met fin aux combats de la Première Guerre mondiale.",
  ),
  annale(
    "an-hg-027",
    "p4-s1",
    7,
    "Depuis quand l'esclavage a-t-il été aboli en France ?",
    "1848",
    ["1789", "1905", "1936"],
    "L'esclavage a été définitivement aboli par le décret du 27 avril 1848.",
  ),
  annale(
    "an-hg-028",
    "p4-s1",
    7,
    "Qui a aboli l'esclavage en France ?",
    "Victor Schœlcher",
    ["Napoléon Ier", "Louis XVI", "Jules Ferry"],
    "Victor Schœlcher a fait adopter le décret d'abolition de l'esclavage en 1848.",
  ),
  annale(
    "an-hg-029",
    "p4-s1",
    7,
    "Depuis quelle année l'école publique est-elle gratuite ?",
    "1881",
    ["1789", "1905", "1945"],
    "La loi Jules Ferry de 1881 rend l'école publique gratuite.",
  ),
  annale(
    "an-hg-030",
    "p4-s1",
    7,
    "En 1944, qu'est-ce qui a changé pour les femmes ?",
    "Elles ont obtenu le droit de vote",
    ["Elles ont pu ouvrir un compte bancaire", "Elles ont obtenu le droit de divorcer", "Elles ont pu travailler sans autorisation"],
    "L'ordonnance du 21 avril 1944 accorde le droit de vote aux femmes, qui votent en 1945.",
  ),
  annale(
    "an-hg-031",
    "p4-s1",
    8,
    "Quelle organisation a été créée en 1945 après la Seconde Guerre mondiale ?",
    "L'Organisation des Nations unies (ONU)",
    ["L'Union européenne", "L'OTAN", "La Société des Nations"],
    "L'ONU est créée en 1945 pour maintenir la paix entre les nations.",
  ),
  annale(
    "an-hg-032",
    "p4-s1",
    8,
    "En quelle année l'euro est-il devenu la monnaie officielle de la France ?",
    "2002",
    ["1992", "1999", "2010"],
    "Les pièces et billets en euros sont entrés en circulation le 1er janvier 2002.",
  ),
  annale(
    "an-hg-033",
    "p4-s1",
    8,
    "Lors de la seconde guerre mondiale, à quelle date la ville de Paris a-t-elle été libérée ?",
    "Le 25 août 1944",
    ["Le 6 juin 1944", "Le 8 mai 1945", "Le 11 novembre 1943"],
    "Paris est libérée le 25 août 1944, après l'insurrection et l'arrivée de la 2e DB du général Leclerc.",
  ),
  annale(
    "an-hg-034",
    "p4-s1",
    8,
    "Quel était le principal port français impliqué dans la traite négrière au XVIIIe siècle ?",
    "Nantes",
    ["Marseille", "Calais", "Nice"],
    "Nantes fut le premier port négrier français au XVIIIe siècle.",
  ),
  annale(
    "an-hg-035",
    "p4-s1",
    8,
    "Quel célèbre philosophe des Lumières a dénoncé l'esclavage ?",
    "Montesquieu",
    ["Descartes", "Pasteur", "Molière"],
    "Montesquieu, comme d'autres philosophes des Lumières, a dénoncé l'esclavage.",
  ),
  annale(
    "an-hg-036",
    "p4-s3",
    8,
    "Quelle œuvre a été écrite par Victor Hugo ?",
    "Les Misérables",
    ["Le Petit Prince", "L'Étranger", "Madame Bovary"],
    "Victor Hugo est l'auteur des Misérables et de Notre-Dame de Paris.",
  ),
  annale(
    "an-hg-037",
    "p4-s3",
    8,
    "Quel peintre est français ?",
    "Claude Monet",
    ["Pablo Picasso", "Vincent Van Gogh", "Léonard de Vinci"],
    "Claude Monet, chef de file de l'impressionnisme, est français.",
  ),
  annale(
    "an-hg-038",
    "p4-s3",
    8,
    "Quel plat est une spécialité de la cuisine française ?",
    "Le bœuf bourguignon",
    ["La paella", "La pizza", "Le sushi"],
    "Le bœuf bourguignon est un plat traditionnel français, originaire de Bourgogne.",
  ),
  annale(
    "an-hg-039",
    "p4-s1",
    8,
    "Qui était Marie Curie ?",
    "Une scientifique, deux fois prix Nobel",
    ["Une romancière", "Une actrice", "Une femme politique"],
    "Marie Curie, physicienne et chimiste, a reçu les prix Nobel de physique (1903) et de chimie (1911).",
  ),
  annale(
    "an-hg-040",
    "p4-s3",
    8,
    "Qui a peint « La liberté guidant le peuple » ?",
    "Eugène Delacroix",
    ["Claude Monet", "Auguste Renoir", "Paul Cézanne"],
    "Ce tableau de Delacroix (1830) est un symbole de la liberté ; il est exposé au Louvre.",
  ),
  annale(
    "an-hg-041",
    "p4-s3",
    8,
    "Dans quel grand musée parisien est exposée la Joconde ?",
    "Le Louvre",
    ["Le musée d'Orsay", "Le Centre Pompidou", "Le musée Rodin"],
    "La Joconde de Léonard de Vinci est exposée au musée du Louvre.",
  ),
  annale(
    "an-hg-042",
    "p4-s3",
    8,
    "Quel château célèbre se trouve près de Paris et symbolise le pouvoir royal de Louis XIV ?",
    "Le château de Versailles",
    ["Le château de Chambord", "Le Mont-Saint-Michel", "Le palais des Papes"],
    "Louis XIV, le Roi-Soleil, a fait de Versailles le siège du pouvoir royal.",
  ),
  annale(
    "an-hg-043",
    "p4-s3",
    8,
    "Où peut-on voir des peintures préhistoriques en France ?",
    "Dans la grotte de Lascaux",
    ["Au château de Versailles", "Dans les catacombes de Paris", "À la Sainte-Chapelle"],
    "La grotte de Lascaux (Dordogne) abrite des peintures préhistoriques célèbres.",
  ),
  annale(
    "an-hg-044",
    "p4-s3",
    8,
    "Quel peintre célèbre a peint les Nymphéas ?",
    "Claude Monet",
    ["Paul Gauguin", "Edgar Degas", "Henri Matisse"],
    "Monet a peint la série des Nymphéas dans son jardin de Giverny.",
  ),
  annale(
    "an-hg-045",
    "p4-s3",
    8,
    "Pendant quelles journées peut-on visiter gratuitement des lieux culturels en France ?",
    "Les Journées européennes du patrimoine",
    ["Les soldes d'été", "La fête de la musique", "Le 1er avril"],
    "Chaque année en septembre, les Journées du patrimoine ouvrent gratuitement de nombreux monuments.",
  ),
  annale(
    "an-hg-046",
    "p4-s1",
    8,
    "Que symbolise le 1er mai ?",
    "La fête du Travail",
    ["La fête nationale", "La fête des mères", "La journée de l'Europe"],
    "Le 1er mai, jour férié, est la fête du Travail ; on y offre traditionnellement du muguet.",
  ),
  annale(
    "an-hg-047",
    "p4-s3",
    8,
    "Qui était Monsieur Rouget de Lisle ?",
    "L'auteur et compositeur de la Marseillaise",
    ["Un roi de France", "Un peintre impressionniste", "Un résistant"],
    "Officier, Rouget de Lisle a composé la Marseillaise en 1792 à Strasbourg.",
  ),
  annale(
    "an-hg-048",
    "p4-s3",
    8,
    "À quelle occasion a été construite la Tour Eiffel ?",
    "L'Exposition universelle de 1889",
    ["Les Jeux olympiques de 1900", "Le sacre de Napoléon", "La visite de la reine Victoria"],
    "Gustave Eiffel l'a construite pour l'Exposition universelle de 1889, centenaire de la Révolution.",
  ),
  annale(
    "an-hg-049",
    "p4-s2",
    8,
    "Quelle chaîne de montagnes est située entre la France et l'Italie ?",
    "Les Alpes",
    ["Les Pyrénées", "Les Vosges", "Le Jura"],
    "Les Alpes séparent la France de l'Italie ; on y trouve le mont Blanc.",
  ),
  annale(
    "an-hg-050",
    "p4-s3",
    8,
    "Qui était Molière ?",
    "Un auteur de théâtre et comédien du XVIIe siècle",
    ["Un peintre", "Un compositeur", "Un scientifique"],
    "Molière (1622-1673) est le grand auteur de comédies français ; on parle de la « langue de Molière ».",
  ),
  annale(
    "an-hg-051",
    "p4-s3",
    8,
    "Qui était Charles Baudelaire ?",
    "Un poète, auteur des Fleurs du mal",
    ["Un sculpteur", "Un homme politique", "Un architecte"],
    "Baudelaire (1821-1867) est l'un des plus grands poètes français.",
  ),
  annale(
    "an-hg-052",
    "p4-s3",
    8,
    "Qui était George Sand ?",
    "Une romancière du XIXe siècle",
    ["Une chanteuse", "Une reine de France", "Une peintre"],
    "George Sand, pseudonyme d'Aurore Dupin, est une grande femme de lettres du XIXe siècle.",
  ),
  annale(
    "an-hg-053",
    "p4-s3",
    8,
    "Qui était Simone de Beauvoir ?",
    "Une philosophe et écrivaine, figure du féminisme",
    ["Une ministre de la Santé", "Une résistante", "Une actrice"],
    "Autrice du Deuxième Sexe (1949), Simone de Beauvoir a marqué la pensée féministe.",
  ),
  annale(
    "an-hg-054",
    "p4-s3",
    8,
    "Qui était Albert Camus ?",
    "Un écrivain, prix Nobel de littérature",
    ["Un peintre", "Un général", "Un chanteur"],
    "Albert Camus, auteur de L'Étranger et de La Peste, a reçu le prix Nobel de littérature en 1957.",
  ),
  annale(
    "an-hg-055",
    "p4-s3",
    8,
    "Qui était Marguerite Yourcenar ?",
    "Une écrivaine, première femme élue à l'Académie française",
    ["Une danseuse étoile", "Une avocate", "Une exploratrice"],
    "Marguerite Yourcenar est entrée à l'Académie française en 1980, une première pour une femme.",
  ),
  annale(
    "an-hg-056",
    "p4-s3",
    8,
    "Qui était Paul Cézanne ?",
    "Un peintre, célèbre pour ses vues de la montagne Sainte-Victoire",
    ["Un romancier", "Un musicien", "Un cinéaste"],
    "Cézanne, peintre d'Aix-en-Provence, a ouvert la voie à la peinture moderne.",
  ),
  annale(
    "an-hg-057",
    "p4-s3",
    8,
    "Qui était Auguste Rodin ?",
    "Un sculpteur, auteur du Penseur",
    ["Un peintre impressionniste", "Un poète", "Un architecte"],
    "Rodin est le plus célèbre sculpteur français (Le Penseur, Le Baiser).",
  ),
  annale(
    "an-hg-058",
    "p4-s3",
    8,
    "Qui était un célèbre compositeur français ?",
    "Claude Debussy",
    ["Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Giuseppe Verdi"],
    "Claude Debussy (1862-1918) est l'un des plus grands compositeurs français.",
  ),
  annale(
    "an-hg-059",
    "p4-s3",
    8,
    "Qui était Auguste Renoir ?",
    "Un peintre impressionniste",
    ["Un sculpteur", "Un écrivain", "Un photographe"],
    "Renoir est un maître de l'impressionnisme (Bal du moulin de la Galette).",
  ),
  annale(
    "an-hg-060",
    "p4-s3",
    8,
    "Quel musée est situé à Paris ?",
    "Le musée d'Orsay",
    ["Le musée du Prado", "Le British Museum", "Les Offices"],
    "Le musée d'Orsay, installé dans une ancienne gare parisienne, abrite les chefs-d'œuvre impressionnistes.",
  ),
  annale(
    "an-hg-061",
    "p4-s2",
    9,
    "Quel monument historique se trouve sur une île en Normandie ?",
    "Le Mont-Saint-Michel",
    ["Le château de Chambord", "Carcassonne", "Le pont du Gard"],
    "Le Mont-Saint-Michel, abbaye bâtie sur un îlot rocheux, est classé au patrimoine mondial.",
  ),
  annale(
    "an-hg-062",
    "p4-s2",
    9,
    "Quelle ville française fait partie des 10 plus grandes métropoles du pays ?",
    "Lyon",
    ["Aurillac", "Guéret", "Mende"],
    "Lyon est, avec Paris et Marseille, l'une des plus grandes métropoles françaises.",
  ),
  annale(
    "an-hg-063",
    "p4-s2",
    9,
    "Quelle île fait partie des Antilles françaises ?",
    "La Guadeloupe",
    ["La Corse", "La Réunion", "Mayotte"],
    "La Guadeloupe et la Martinique sont les Antilles françaises, dans l'océan Atlantique.",
  ),
  annale(
    "an-hg-064",
    "p4-s2",
    9,
    "Quelle île est française ?",
    "La Corse",
    ["La Sardaigne", "La Sicile", "Malte"],
    "La Corse est une île française de Méditerranée.",
  ),
  annale(
    "an-hg-065",
    "p4-s2",
    9,
    "Quelle est la plus haute montagne de France ?",
    "Le mont Blanc",
    ["Le puy de Dôme", "Le pic du Midi", "Le mont Ventoux"],
    "Le mont Blanc (4 806 m), dans les Alpes, est le plus haut sommet de France et d'Europe occidentale.",
  ),
  annale(
    "an-hg-066",
    "p4-s2",
    9,
    "Quelle île française est située dans l'océan indien ?",
    "La Réunion",
    ["La Martinique", "La Corse", "Saint-Pierre-et-Miquelon"],
    "La Réunion est un département français de l'océan Indien.",
  ),
  annale(
    "an-hg-067",
    "p4-s2",
    9,
    "Quel département français a une frontière avec le Brésil ?",
    "La Guyane",
    ["La Martinique", "Mayotte", "La Réunion"],
    "La Guyane, en Amérique du Sud, partage plus de 700 km de frontière avec le Brésil.",
  ),
  annale(
    "an-hg-068",
    "p4-s2",
    9,
    "De quelle ville française décolle la fusée Ariane ?",
    "Kourou",
    ["Toulouse", "Bordeaux", "Marseille"],
    "Le Centre spatial guyanais, d'où décolle Ariane, est situé à Kourou, en Guyane.",
  ),
  annale(
    "an-hg-069",
    "p4-s2",
    9,
    "Quelle mer ou océan borde la France métropolitaine ?",
    "La mer Méditerranée",
    ["La mer Noire", "La mer Baltique", "L'océan Indien"],
    "La métropole est bordée par la Manche, l'Atlantique, la mer du Nord et la Méditerranée.",
  ),
  annale(
    "an-hg-070",
    "p4-s2",
    9,
    "Quelle mer se situe entre la France et l'Angleterre ?",
    "La Manche",
    ["La mer du Nord", "La mer Méditerranée", "La mer d'Iroise"],
    "La Manche sépare la France du Royaume-Uni ; un tunnel la traverse depuis 1994.",
  ),
  annale(
    "an-hg-071",
    "p4-s2",
    9,
    "Quelle île est un département d'outre-mer français ?",
    "La Martinique",
    ["Malte", "La Sicile", "Chypre"],
    "La Martinique est l'un des cinq départements et régions d'outre-mer.",
  ),
  annale(
    "an-hg-072",
    "p4-s2",
    9,
    "Qu'est-ce que la France d'outre-mer ?",
    "Les territoires français situés hors d'Europe",
    ["Les pays frontaliers de la France", "Les anciennes colonies devenues indépendantes", "Les zones maritimes internationales"],
    "La France d'outre-mer regroupe les territoires français des océans Atlantique, Indien et Pacifique.",
  ),
  annale(
    "an-hg-073",
    "p4-s2",
    9,
    "Quelle est la population approximative de la France en 2025 ?",
    "68 millions d'habitants",
    ["50 millions", "80 millions", "95 millions"],
    "La France compte environ 68 millions d'habitants, outre-mer compris.",
  ),
  annale(
    "an-hg-074",
    "p4-s2",
    9,
    "Quel est le principal port maritime de France ?",
    "Marseille",
    ["Paris", "Lyon", "Strasbourg"],
    "Marseille est le premier port maritime français.",
  ),
  annale(
    "an-hg-075",
    "p4-s2",
    9,
    "Combien y a-t-il de régions en France métropolitaine ?",
    "13",
    ["22", "17", "9"],
    "Depuis 2016, la métropole compte 13 régions (18 avec l'outre-mer).",
  ),
  annale(
    "an-hg-076",
    "p4-s2",
    9,
    "Quelle chaîne de montagnes est située entre la France et l'Espagne ?",
    "Les Pyrénées",
    ["Les Alpes", "Le Massif central", "Les Vosges"],
    "Les Pyrénées forment la frontière naturelle entre la France et l'Espagne.",
  ),
  annale(
    "an-hg-077",
    "p4-s2",
    9,
    "Quelle île française se trouve au sud-est du continent africain ?",
    "Mayotte",
    ["La Guadeloupe", "La Corse", "Tahiti"],
    "Mayotte, département français, est située dans le canal du Mozambique, au sud-est de l'Afrique.",
  ),
  annale(
    "an-hg-078",
    "p4-s2",
    9,
    "Quel est le chef-lieu de la région Auvergne-Rhône-Alpes ?",
    "Lyon",
    ["Clermont-Ferrand", "Grenoble", "Saint-Étienne"],
    "Lyon est le chef-lieu de la région Auvergne-Rhône-Alpes.",
  ),
  annale(
    "an-hg-079",
    "p4-s2",
    9,
    "Quel est le chef-lieu de la région Bretagne ?",
    "Rennes",
    ["Brest", "Nantes", "Quimper"],
    "Rennes est le chef-lieu de la région Bretagne.",
  ),
  annale(
    "an-hg-080",
    "p4-s2",
    9,
    "Quel est le chef-lieu de la région Provence-Alpes-Côte d'Azur ?",
    "Marseille",
    ["Nice", "Toulon", "Avignon"],
    "Marseille est le chef-lieu de la région Provence-Alpes-Côte d'Azur.",
  ),
  annale(
    "an-hg-081",
    "p4-s2",
    9,
    "Quel est le 101ème département français depuis 2011 ?",
    "Mayotte",
    ["La Guyane", "La Corse-du-Sud", "Saint-Martin"],
    "Mayotte est devenue le 101e département français en 2011.",
  ),
  annale(
    "an-hg-082",
    "p4-s2",
    9,
    "Quelle région française est réputée pour ses stations de ski ?",
    "Auvergne-Rhône-Alpes",
    ["La Bretagne", "Les Pays de la Loire", "La Normandie"],
    "Les Alpes, en région Auvergne-Rhône-Alpes, concentrent les grandes stations de ski françaises.",
  ),
  annale(
    "an-hg-083",
    "p4-s2",
    9,
    "Quel fleuve traverse Paris ?",
    "La Seine",
    ["La Loire", "Le Rhône", "La Garonne"],
    "La Seine traverse Paris avant de se jeter dans la Manche au Havre.",
  ),
];
