import type { Qcm } from "../types";
import { annale } from "./helpers";

/**
 * Annales officielles — thème « Principes et valeurs de la République ».
 * Intitulés issus du document « Questions de connaissance » du ministère de
 * l'Intérieur (12 décembre 2025), pages 1-2. Choix et corrections rédigés
 * d'après le Livret du citoyen 2026.
 */
export const annalesPrincipes: Qcm[] = [
  annale(
    "an-pv-001",
    "p1-s1",
    1,
    "Complétez les paroles de la Marseillaise « Allons enfants de la patrie… »",
    "Le jour de gloire est arrivé !",
    [
      "Le jour de colère est arrivé !",
      "L'heure de gloire est arrivée !",
      "Le jour de victoire est arrivé !",
    ],
    "La Marseillaise commence par « Allons enfants de la patrie, le jour de gloire est arrivé ! ».",
  ),
  annale(
    "an-pv-002",
    "p1-s2",
    1,
    "Dans le cadre d'un entretien d'embauche, que peut-on demander au candidat ?",
    "Son expérience et ses compétences professionnelles",
    [
      "Sa situation familiale et son projet d'avoir des enfants",
      "Son lieu de naissance et ses origines familiales",
      "Son appartenance syndicale et ses engagements passés",
    ],
    "Seules les questions liées au poste sont permises : religion, opinions ou santé relèvent de la vie privée et les discriminations sont interdites.",
  ),
  annale(
    "an-pv-003",
    "p1-s2",
    1,
    "Déclarer ses revenus aux services fiscaux est :",
    "Une obligation légale",
    [
      "Obligatoire uniquement si l'on est imposable",
      "Obligatoire uniquement pour les salariés",
      "Facultatif la première année en France",
    ],
    "Chaque foyer doit déclarer ses revenus chaque année : l'impôt finance les services publics.",
  ),
  annale(
    "an-pv-004",
    "p1-s2",
    1,
    "En France, les impôts permettent de financer les dépenses publiques. Quelle proposition est correcte ?",
    "Ils financent les écoles, les hôpitaux et les routes",
    [
      "Ils financent uniquement la défense et la police",
      "Ils servent seulement à rembourser la dette de l'État",
      "Ils financent l'entretien des lieux de culte construits après 1905",
    ],
    "Les impôts financent les services publics : éducation, santé, sécurité, infrastructures.",
  ),
  annale(
    "an-pv-005",
    "p1-s2",
    1,
    "La liberté d'association est :",
    "Un droit fondamental garanti par la loi",
    [
      "Un droit soumis à l'autorisation préalable du préfet",
      "Un droit réservé aux personnes de nationalité française",
      "Un droit accordé uniquement aux personnes majeures",
    ],
    "Depuis la loi de 1901, chacun peut créer ou rejoindre librement une association.",
  ),
  annale(
    "an-pv-006",
    "p1-s2",
    1,
    "La liberté d'expression sur les réseaux sociaux en France est :",
    "Autorisée, mais encadrée par la loi",
    [
      "Totale, car internet échappe à la loi française",
      "Autorisée uniquement sous son vrai nom",
      "Autorisée, sauf pour critiquer le gouvernement",
    ],
    "On peut s'exprimer librement, mais l'injure, la diffamation et l'incitation à la haine sont punies par la loi.",
  ),
  annale(
    "an-pv-007",
    "p1-s1",
    1,
    "Lequel de ces prénoms évoque un symbole de la République ?",
    "Marianne",
    ["Jeanne", "Joséphine", "Anne"],
    "Marianne est la figure allégorique de la République française.",
  ),
  annale(
    "an-pv-008",
    "p1-s1",
    1,
    "Lequel de ces symboles représente la République française ?",
    "Le drapeau bleu, blanc, rouge",
    ["La fleur de lys", "L'aigle impérial", "La croix de Lorraine"],
    "Le drapeau tricolore est le symbole officiel de la République (article 2 de la Constitution).",
  ),
  annale(
    "an-pv-009",
    "p1-s1",
    1,
    "Où peut-on voir la devise de la République ?",
    "Sur le fronton des mairies et des bâtiments publics",
    [
      "Sur les panneaux d'entrée de ville",
      "Sur les plaques d'immatriculation",
      "À l'entrée des lieux de culte",
    ],
    "« Liberté, Égalité, Fraternité » figure sur les frontons des mairies, des écoles et des bâtiments publics.",
  ),
  annale(
    "an-pv-010",
    "p1-s1",
    1,
    "Lesquels sont des symboles officiels de la République française ?",
    "Le drapeau tricolore et La Marseillaise",
    [
      "Le coq gaulois et la croix de Lorraine",
      "Le drapeau tricolore et la fleur de lys",
      "La Marseillaise et l'aigle impérial",
    ],
    "La Constitution reconnaît le drapeau tricolore, La Marseillaise, la devise et le principe du gouvernement du peuple.",
  ),
  annale(
    "an-pv-011",
    "p1-s1",
    1,
    "Peut-on brûler publiquement un drapeau français ?",
    "Non, l'outrage public au drapeau est puni par la loi",
    [
      "Oui, au nom de la liberté d'expression",
      "Oui, lors d'une manifestation déclarée",
      "Oui, si le drapeau vous appartient",
    ],
    "L'outrage au drapeau tricolore commis en public est une infraction pénale.",
  ),
  annale(
    "an-pv-012",
    "p1-s2",
    1,
    "Quand la sécurité sociale a-t-elle été établie en France ?",
    "En 1945",
    ["En 1936", "En 1958", "En 1968"],
    "La Sécurité sociale a été créée en 1945, à la Libération.",
  ),
  annale(
    "an-pv-013",
    "p1-s1",
    1,
    "Que commémore la fête nationale ?",
    "La prise de la Bastille du 14 juillet 1789",
    [
      "La proclamation de la République du 22 septembre 1792",
      "L'abolition des privilèges du 4 août 1789",
      "La Déclaration des droits de l'homme du 26 août 1789",
    ],
    "Le 14 juillet commémore la prise de la Bastille (1789) et la fête de la Fédération (1790).",
  ),
  annale(
    "an-pv-014",
    "p1-s1",
    1,
    "Que porte Marianne sur la tête ?",
    "Un bonnet phrygien",
    ["Une couronne de lauriers", "Une cocarde tricolore", "Un diadème étoilé"],
    "Le bonnet phrygien, hérité des esclaves affranchis de l'Antiquité, symbolise la liberté.",
  ),
  annale(
    "an-pv-015",
    "p1-s1",
    1,
    "Que signifie le mot « fraternité » dans la devise française ?",
    "La solidarité entre tous les membres de la société",
    [
      "L'égalité de tous devant la loi",
      "Le droit de penser et de s'exprimer librement",
      "L'attachement à la nation et à ses traditions",
    ],
    "La fraternité, c'est l'entraide et la solidarité qui unissent les citoyens.",
  ),
  annale(
    "an-pv-016",
    "p1-s1",
    1,
    "Quel symbole de la République peut-on voir sur les maillots de l'équipe de France de football ?",
    "Le coq",
    ["Marianne", "Le bonnet phrygien", "Le faisceau de licteur"],
    "Le coq gaulois figure sur les maillots des équipes de France.",
  ),
  annale(
    "an-pv-017",
    "p1-s1",
    1,
    "Quelle est la devise de la République française ?",
    "Liberté, Égalité, Fraternité",
    ["Liberté, Égalité, Solidarité", "Liberté, Justice, Fraternité", "Unité, Égalité, Fraternité"],
    "La devise officielle de la République est « Liberté, Égalité, Fraternité » (article 2 de la Constitution).",
  ),
  annale(
    "an-pv-018",
    "p1-s2",
    1,
    "Qu'est-ce que la liberté d'association ?",
    "Le droit de créer ou de rejoindre une association librement",
    [
      "Le droit de manifester sur la voie publique sans déclaration",
      "Le droit de créer une association après accord du maire",
      "Le droit pour toute association de recevoir des subventions",
    ],
    "Toute personne peut fonder une association ou en devenir membre, sans autorisation préalable.",
  ),
  annale(
    "an-pv-019",
    "p1-s2",
    1,
    "Qu'est-ce qu'une liberté ?",
    "Un droit fondamental de faire tout ce qui ne nuit pas à autrui",
    [
      "Un droit de faire tout ce que la morale religieuse autorise",
      "Un droit de faire seulement ce que l'État a expressément permis",
      "Un droit de faire tout ce que l'on veut, du moment qu'on est chez soi",
    ],
    "Selon la DDHC de 1789, la liberté consiste à pouvoir faire tout ce qui ne nuit pas à autrui.",
  ),
  annale(
    "an-pv-020",
    "p1-s2",
    1,
    "Selon la Constitution, la France est une République…",
    "Indivisible, laïque, démocratique et sociale",
    [
      "Indivisible, laïque, démocratique et libérale",
      "Unie, laïque, fédérale et sociale",
      "Indivisible, neutre, parlementaire et sociale",
    ],
    "L'article 1er de la Constitution : « La France est une République indivisible, laïque, démocratique et sociale. »",
  ),
  annale(
    "an-pv-021",
    "p1-s1",
    1,
    "Sur quel document peut-on voir Marianne ?",
    "Sur les timbres postaux",
    ["Sur les billets en euros", "Sur la carte Vitale", "Sur les tickets de métro"],
    "Marianne figure notamment sur les timbres, ainsi que sur les documents officiels de l'État.",
  ),
  annale(
    "an-pv-022",
    "p1-s1",
    1,
    "Une des valeurs de la devise républicaine est l'Égalité. Qu'est-ce que cela signifie ?",
    "La loi est la même pour tous, sans distinction",
    [
      "Chacun reçoit les mêmes aides, quelle que soit sa situation",
      "Chacun paie le même montant d'impôt",
      "Seuls les citoyens français ont des droits",
    ],
    "L'égalité signifie que tous les citoyens ont les mêmes droits et sont égaux devant la loi.",
  ),
  annale(
    "an-pv-023",
    "p1-s2",
    1,
    "Une personne peut-elle changer librement de religion en France ?",
    "Oui, la liberté de conscience le garantit",
    [
      "Oui, mais il faut le déclarer à la mairie",
      "Non, sauf en cas de mariage",
      "Oui, mais une seule fois après sa majorité",
    ],
    "Chacun est libre de croire, de ne pas croire ou de changer de religion : c'est la liberté de conscience.",
  ),
  annale(
    "an-pv-024",
    "p1-s2",
    1,
    "Selon le principe de laïcité, que signifie la neutralité de l'État ?",
    "L'État ne privilégie et ne finance aucune religion",
    [
      "L'État finance tous les cultes de manière égale",
      "L'État interdit les signes religieux dans la rue",
      "L'État ne reconnaît que les grandes religions",
    ],
    "L'État est neutre : il garantit la liberté de culte mais ne reconnaît, ne salarie ni ne subventionne aucun culte.",
  ),
  annale(
    "an-pv-025",
    "p1-s2",
    1,
    "Que peut faire un usager du service public dans une mairie ?",
    "Demander un acte d'état civil ou faire ses démarches administratives",
    [
      "Demander ou renouveler son titre de séjour",
      "Déposer une plainte pour un vol",
      "Demander le versement de ses allocations familiales",
    ],
    "La mairie délivre les actes d'état civil (naissance, mariage, décès) et accompagne les démarches des habitants.",
  ),
  annale(
    "an-pv-026",
    "p1-s2",
    1,
    "En France, il est possible pour l'État de financer :",
    "L'entretien des édifices religieux construits avant 1905",
    [
      "Le salaire des responsables religieux",
      "La construction de nouveaux lieux de culte",
      "L'organisation des fêtes religieuses",
    ],
    "Les édifices religieux antérieurs à 1905 appartiennent aux collectivités publiques, qui peuvent les entretenir ; les cultes eux-mêmes ne sont pas financés.",
  ),
  annale(
    "an-pv-027",
    "p1-s2",
    1,
    "En quelle année la loi de séparation des Églises et de l'État a-t-elle été votée ?",
    "1905",
    ["1882", "1789", "1946"],
    "La loi du 9 décembre 1905 sépare les Églises et l'État : c'est le fondement de la laïcité.",
  ),
  annale(
    "an-pv-028",
    "p1-s2",
    1,
    "Que dit la loi de 1905 ?",
    "La République ne reconnaît, ne salarie ni ne subventionne aucun culte",
    [
      "L'État reconnaît et finance les principales religions",
      "Les signes religieux sont interdits dans l'espace public",
      "Les ministres des cultes sont nommés par l'État",
    ],
    "La loi de 1905 garantit la liberté de conscience et le libre exercice des cultes, sans reconnaissance officielle.",
  ),
  annale(
    "an-pv-029",
    "p1-s2",
    1,
    "Que garantit le principe de laïcité ?",
    "La liberté de croire ou de ne pas croire",
    [
      "La neutralité religieuse de chaque citoyen en public",
      "Un financement égal de toutes les religions",
      "La primauté des religions historiques de la France",
    ],
    "La laïcité garantit la liberté de conscience et l'égalité de tous, quelle que soit leur croyance.",
  ),
  annale(
    "an-pv-030",
    "p1-s2",
    1,
    "Quel jour célèbre-t-on officiellement la laïcité en France ?",
    "Le 9 décembre",
    ["Le 26 août", "Le 4 août", "Le 22 septembre"],
    "Le 9 décembre, anniversaire de la loi de 1905, est la journée de la laïcité.",
  ),
  annale(
    "an-pv-031",
    "p1-s2",
    2,
    "Quel symbole religieux peut être porté dans une école publique dans le respect de la laïcité ?",
    "Un signe discret, comme une petite médaille",
    [
      "Un voile, s'il est porté avec discrétion",
      "Une grande croix, si l'élève est majeur",
      "Aucun, même discret",
    ],
    "La loi de 2004 interdit aux élèves les signes religieux ostensibles à l'école publique ; les signes discrets restent permis.",
  ),
  annale(
    "an-pv-032",
    "p1-s2",
    2,
    "Quel terme désigne précisément la haine ou les préjugés contre les Juifs ?",
    "L'antisémitisme",
    ["Le racisme", "La xénophobie", "L'intégrisme"],
    "L'antisémitisme désigne la haine et les discriminations visant les Juifs ; il est puni par la loi.",
  ),
  annale(
    "an-pv-033",
    "p1-s2",
    2,
    "Quel texte est considéré comme le texte fondateur de la laïcité ?",
    "La loi du 9 décembre 1905",
    [
      "La Déclaration des droits de l'homme de 1789",
      "La Constitution de 1958",
      "Les lois Jules Ferry de 1882",
    ],
    "La loi de 1905 de séparation des Églises et de l'État fonde la laïcité française.",
  ),
  annale(
    "an-pv-034",
    "p1-s2",
    2,
    "Quelle institution française doit rester neutre en matière de religion ?",
    "L'école publique",
    ["Les associations cultuelles", "Les écoles privées sous contrat", "Les aumôneries"],
    "Les services publics, et notamment l'école publique, sont soumis à la neutralité religieuse.",
  ),
  annale(
    "an-pv-035",
    "p1-s2",
    2,
    "Qu'est-ce que la laïcité ?",
    "La séparation des Églises et de l'État et la liberté de conscience",
    [
      "L'interdiction des religions dans l'espace public",
      "Un financement égal de toutes les religions par l'État",
      "La reconnaissance officielle des grandes religions",
    ],
    "La laïcité repose sur la liberté de conscience, la séparation des Églises et de l'État et l'égalité de tous devant la loi.",
  ),
  annale(
    "an-pv-036",
    "p1-s2",
    2,
    "À l'école, la charte de la laïcité permet de :",
    "Rappeler les règles de la laïcité et du vivre-ensemble",
    [
      "Interdire l'enseignement du fait religieux",
      "Permettre aux familles de choisir les cours suivis",
      "Fixer le calendrier des fêtes religieuses à l'école",
    ],
    "Affichée dans les écoles, la charte de la laïcité explique le sens et les règles de la laïcité à l'école.",
  ),
  annale(
    "an-pv-037",
    "p1-s2",
    2,
    "Qui doit respecter et veiller à la neutralité religieuse dans les services publics ?",
    "Les agents du service public",
    ["Les usagers du service public", "Uniquement les enseignants", "Les représentants des cultes"],
    "Tous les agents publics sont tenus à la neutralité religieuse dans l'exercice de leurs fonctions.",
  ),
  annale(
    "an-pv-038",
    "p1-s2",
    2,
    "Une personne déclare ne croire en aucun dieu. On peut dire :",
    "Qu'elle est athée, et c'est son droit",
    [
      "Qu'elle est agnostique, et c'est son droit",
      "Qu'elle est laïque, et c'est son droit",
      "Qu'elle est apatride, et c'est son droit",
    ],
    "La liberté de conscience protège aussi le droit de ne pas croire.",
  ),
];
