import type { Qcm } from "../types";
import { annale } from "./helpers";

/**
 * Annales officielles — thème « Principes et valeurs de la République ».
 * Intitulés issus du document « Questions de connaissance » du ministère de
 * l'Intérieur (12 décembre 2025), pages 1-2. Choix et corrections rédigés
 * d'après le Livret du citoyen 2026.
 */
export const annalesPrincipes: Qcm[] = [
  annale(
    "an-pv-001",
    "p1-s1",
    1,
    "Complétez les paroles de la Marseillaise « Allons enfants de la patrie… »",
    "Le jour de gloire est arrivé !",
    ["La victoire en chantant", "Aux armes citoyens !", "L'étendard sanglant est levé"],
    "La Marseillaise commence par « Allons enfants de la patrie, le jour de gloire est arrivé ! ».",
  ),
  annale(
    "an-pv-002",
    "p1-s2",
    1,
    "Dans le cadre d'un entretien d'embauche, que peut-on demander au candidat ?",
    "Son expérience et ses compétences professionnelles",
    ["Sa religion", "Ses opinions politiques", "Son état de santé"],
    "Seules les questions liées au poste sont permises : religion, opinions ou santé relèvent de la vie privée et les discriminations sont interdites.",
  ),
  annale(
    "an-pv-003",
    "p1-s2",
    1,
    "Déclarer ses revenus aux services fiscaux est :",
    "Une obligation légale",
    ["Un choix personnel", "Réservé aux plus riches", "Facultatif si on gagne peu"],
    "Chaque foyer doit déclarer ses revenus chaque année : l'impôt finance les services publics.",
  ),
  annale(
    "an-pv-004",
    "p1-s2",
    1,
    "En France, les impôts permettent de financer les dépenses publiques. Quelle proposition est correcte ?",
    "Ils financent les écoles, les hôpitaux et les routes",
    [
      "Ils financent uniquement l'armée",
      "Ils sont reversés directement au président de la République",
      "Ils financent les cultes religieux",
    ],
    "Les impôts financent les services publics : éducation, santé, sécurité, infrastructures.",
  ),
  annale(
    "an-pv-005",
    "p1-s2",
    1,
    "La liberté d'association est :",
    "Un droit fondamental garanti par la loi",
    ["Réservée aux Français de naissance", "Soumise à autorisation du préfet", "Interdite aux mineurs"],
    "Depuis la loi de 1901, chacun peut créer ou rejoindre librement une association.",
  ),
  annale(
    "an-pv-006",
    "p1-s2",
    1,
    "La liberté d'expression sur les réseaux sociaux en France est :",
    "Autorisée, mais encadrée par la loi",
    ["Totale et sans aucune limite", "Interdite", "Réservée aux journalistes"],
    "On peut s'exprimer librement, mais l'injure, la diffamation et l'incitation à la haine sont punies par la loi.",
  ),
  annale(
    "an-pv-007",
    "p1-s1",
    1,
    "Lequel de ces prénoms évoque un symbole de la République ?",
    "Marianne",
    ["Jeanne", "Charlotte", "Louise"],
    "Marianne est la figure allégorique de la République française.",
  ),
  annale(
    "an-pv-008",
    "p1-s1",
    1,
    "Lequel de ces symboles représente la République française ?",
    "Le drapeau bleu, blanc, rouge",
    ["L'aigle impérial", "La fleur de lys", "La croix de Lorraine"],
    "Le drapeau tricolore est le symbole officiel de la République (article 2 de la Constitution).",
  ),
  annale(
    "an-pv-009",
    "p1-s1",
    1,
    "Où peut-on voir la devise de la République ?",
    "Sur le fronton des mairies et des bâtiments publics",
    ["Sur les plaques d'immatriculation", "Sur les billets de banque uniquement", "Sur les panneaux d'autoroute"],
    "« Liberté, Égalité, Fraternité » figure sur les frontons des mairies, des écoles et des bâtiments publics.",
  ),
  annale(
    "an-pv-010",
    "p1-s1",
    1,
    "Lesquels sont des symboles officiels de la République française ?",
    "Le drapeau tricolore et La Marseillaise",
    ["Le coq et la baguette", "La tour Eiffel et le béret", "Le lys et la couronne"],
    "La Constitution reconnaît le drapeau tricolore, La Marseillaise, la devise et le principe du gouvernement du peuple.",
  ),
  annale(
    "an-pv-011",
    "p1-s1",
    1,
    "Peut-on brûler publiquement un drapeau français ?",
    "Non, l'outrage public au drapeau est puni par la loi",
    ["Oui, c'est une liberté d'expression", "Oui, sauf le 14 juillet", "Oui, avec une autorisation"],
    "L'outrage au drapeau tricolore commis en public est une infraction pénale.",
  ),
  annale(
    "an-pv-012",
    "p1-s2",
    1,
    "Quand la sécurité sociale a-t-elle été établie en France ?",
    "En 1945",
    ["En 1905", "En 1789", "En 1981"],
    "La Sécurité sociale a été créée en 1945, à la Libération.",
  ),
  annale(
    "an-pv-013",
    "p1-s1",
    1,
    "Que commémore la fête nationale ?",
    "La prise de la Bastille du 14 juillet 1789",
    ["Le sacre de Napoléon", "La fin de la Première Guerre mondiale", "La naissance du général de Gaulle"],
    "Le 14 juillet commémore la prise de la Bastille (1789) et la fête de la Fédération (1790).",
  ),
  annale(
    "an-pv-014",
    "p1-s1",
    1,
    "Que porte Marianne sur la tête ?",
    "Un bonnet phrygien",
    ["Une couronne de lauriers", "Un béret", "Une couronne royale"],
    "Le bonnet phrygien, hérité des esclaves affranchis de l'Antiquité, symbolise la liberté.",
  ),
  annale(
    "an-pv-015",
    "p1-s1",
    1,
    "Que signifie le mot « fraternité » dans la devise française ?",
    "La solidarité entre tous les membres de la société",
    ["L'obligation d'avoir des frères et sœurs", "L'amour de la patrie", "L'égalité devant l'impôt"],
    "La fraternité, c'est l'entraide et la solidarité qui unissent les citoyens.",
  ),
  annale(
    "an-pv-016",
    "p1-s1",
    1,
    "Quel symbole de la République peut-on voir sur les maillots de l'équipe de France de football ?",
    "Le coq",
    ["Marianne", "Le bonnet phrygien", "La devise républicaine"],
    "Le coq gaulois figure sur les maillots des équipes de France.",
  ),
  annale(
    "an-pv-017",
    "p1-s1",
    1,
    "Quelle est la devise de la République française ?",
    "Liberté, Égalité, Fraternité",
    ["Travail, Famille, Patrie", "Unie dans la diversité", "Dieu et mon droit"],
    "La devise officielle de la République est « Liberté, Égalité, Fraternité » (article 2 de la Constitution).",
  ),
  annale(
    "an-pv-018",
    "p1-s2",
    1,
    "Qu'est-ce que la liberté d'association ?",
    "Le droit de créer ou de rejoindre une association librement",
    [
      "L'obligation d'adhérer à une association",
      "Le droit de créer une entreprise sans impôts",
      "Un droit réservé aux partis politiques",
    ],
    "Toute personne peut fonder une association ou en devenir membre, sans autorisation préalable.",
  ),
  annale(
    "an-pv-019",
    "p1-s2",
    1,
    "Qu'est-ce qu'une liberté ?",
    "Un droit fondamental de faire tout ce qui ne nuit pas à autrui",
    [
      "Le droit de faire absolument tout ce que l'on veut",
      "Une permission accordée par le maire",
      "Un privilège réservé aux citoyens français",
    ],
    "Selon la DDHC de 1789, la liberté consiste à pouvoir faire tout ce qui ne nuit pas à autrui.",
  ),
  annale(
    "an-pv-020",
    "p1-s2",
    1,
    "Selon la Constitution, la France est une République…",
    "Indivisible, laïque, démocratique et sociale",
    ["Fédérale, monarchique et religieuse", "Unie, chrétienne et libérale", "Centralisée, militaire et souveraine"],
    "L'article 1er de la Constitution : « La France est une République indivisible, laïque, démocratique et sociale. »",
  ),
  annale(
    "an-pv-021",
    "p1-s1",
    1,
    "Sur quel document peut-on voir Marianne ?",
    "Sur les timbres postaux",
    ["Sur le permis de conduire", "Sur la carte bancaire", "Sur le carnet de santé"],
    "Marianne figure notamment sur les timbres, ainsi que sur les documents officiels de l'État.",
  ),
  annale(
    "an-pv-022",
    "p1-s1",
    1,
    "Une des valeurs de la devise républicaine est l'Égalité. Qu'est-ce que cela signifie ?",
    "La loi est la même pour tous, sans distinction",
    [
      "Tout le monde gagne le même salaire",
      "Tous les citoyens ont le même métier",
      "Chacun paie le même montant d'impôts",
    ],
    "L'égalité signifie que tous les citoyens ont les mêmes droits et sont égaux devant la loi.",
  ),
  annale(
    "an-pv-023",
    "p1-s2",
    1,
    "Une personne peut-elle changer librement de religion en France ?",
    "Oui, la liberté de conscience le garantit",
    ["Non, c'est interdit", "Oui, avec l'accord du préfet", "Seulement une fois dans sa vie"],
    "Chacun est libre de croire, de ne pas croire ou de changer de religion : c'est la liberté de conscience.",
  ),
  annale(
    "an-pv-024",
    "p1-s2",
    1,
    "Selon le principe de laïcité, que signifie la neutralité de l'État ?",
    "L'État ne privilégie et ne finance aucune religion",
    [
      "L'État interdit toutes les religions",
      "L'État choisit une religion officielle",
      "L'État ne s'occupe d'aucun sujet de société",
    ],
    "L'État est neutre : il garantit la liberté de culte mais ne reconnaît, ne salarie ni ne subventionne aucun culte.",
  ),
  annale(
    "an-pv-025",
    "p1-s2",
    1,
    "Que peut faire un usager du service public dans une mairie ?",
    "Demander un acte d'état civil ou faire ses démarches administratives",
    ["Voter à n'importe quelle date", "Payer ses achats", "Faire ses courses alimentaires"],
    "La mairie délivre les actes d'état civil (naissance, mariage, décès) et accompagne les démarches des habitants.",
  ),
  annale(
    "an-pv-026",
    "p1-s2",
    1,
    "En France, il est possible pour l'État de financer :",
    "L'entretien des édifices religieux construits avant 1905",
    ["Le salaire des ministres du culte", "La construction de nouveaux lieux de culte", "Les activités religieuses des associations"],
    "Les édifices religieux antérieurs à 1905 appartiennent aux collectivités publiques, qui peuvent les entretenir ; les cultes eux-mêmes ne sont pas financés.",
  ),
  annale(
    "an-pv-027",
    "p1-s2",
    1,
    "En quelle année la loi de séparation des Églises et de l'État a-t-elle été votée ?",
    "1905",
    ["1789", "1945", "1958"],
    "La loi du 9 décembre 1905 sépare les Églises et l'État : c'est le fondement de la laïcité.",
  ),
  annale(
    "an-pv-028",
    "p1-s2",
    1,
    "Que dit la loi de 1905 ?",
    "La République ne reconnaît, ne salarie ni ne subventionne aucun culte",
    [
      "La religion catholique est la religion officielle",
      "Les religions sont interdites en public",
      "L'État nomme les responsables religieux",
    ],
    "La loi de 1905 garantit la liberté de conscience et le libre exercice des cultes, sans reconnaissance officielle.",
  ),
  annale(
    "an-pv-029",
    "p1-s2",
    1,
    "Que garantit le principe de laïcité ?",
    "La liberté de croire ou de ne pas croire",
    ["L'interdiction de toute religion", "Une religion d'État", "L'obligation d'être athée"],
    "La laïcité garantit la liberté de conscience et l'égalité de tous, quelle que soit leur croyance.",
  ),
  annale(
    "an-pv-030",
    "p1-s2",
    1,
    "Quel jour célèbre-t-on officiellement la laïcité en France ?",
    "Le 9 décembre",
    ["Le 14 juillet", "Le 1er mai", "Le 11 novembre"],
    "Le 9 décembre, anniversaire de la loi de 1905, est la journée de la laïcité.",
  ),
  annale(
    "an-pv-031",
    "p1-s2",
    2,
    "Quel symbole religieux peut être porté dans une école publique dans le respect de la laïcité ?",
    "Un signe discret, comme une petite médaille",
    ["Aucun, même discret", "Tous les signes, sans limite", "Uniquement les signes chrétiens"],
    "La loi de 2004 interdit aux élèves les signes religieux ostensibles à l'école publique ; les signes discrets restent permis.",
  ),
  annale(
    "an-pv-032",
    "p1-s2",
    2,
    "Quel terme désigne précisément la haine ou les préjugés contre les Juifs ?",
    "L'antisémitisme",
    ["Le racisme", "La xénophobie", "Le sexisme"],
    "L'antisémitisme désigne la haine et les discriminations visant les Juifs ; il est puni par la loi.",
  ),
  annale(
    "an-pv-033",
    "p1-s2",
    2,
    "Quel texte est considéré comme le texte fondateur de la laïcité ?",
    "La loi du 9 décembre 1905",
    ["La Constitution de 1958", "Le Code civil", "Le traité de Rome"],
    "La loi de 1905 de séparation des Églises et de l'État fonde la laïcité française.",
  ),
  annale(
    "an-pv-034",
    "p1-s2",
    2,
    "Quelle institution française doit rester neutre en matière de religion ?",
    "L'école publique",
    ["Les associations cultuelles", "Les lieux de culte", "Les écoles privées confessionnelles"],
    "Les services publics, et notamment l'école publique, sont soumis à la neutralité religieuse.",
  ),
  annale(
    "an-pv-035",
    "p1-s2",
    2,
    "Qu'est-ce que la laïcité ?",
    "La séparation des Églises et de l'État et la liberté de conscience",
    [
      "L'interdiction de pratiquer une religion",
      "L'obligation d'appartenir à une religion",
      "Le financement public des cultes",
    ],
    "La laïcité repose sur la liberté de conscience, la séparation des Églises et de l'État et l'égalité de tous devant la loi.",
  ),
  annale(
    "an-pv-036",
    "p1-s2",
    2,
    "À l'école, la charte de la laïcité permet de :",
    "Rappeler les règles de la laïcité et du vivre-ensemble",
    [
      "Choisir la religion enseignée aux élèves",
      "Dispenser certains élèves de cours",
      "Interdire les cours d'histoire des religions",
    ],
    "Affichée dans les écoles, la charte de la laïcité explique le sens et les règles de la laïcité à l'école.",
  ),
  annale(
    "an-pv-037",
    "p1-s2",
    2,
    "Qui doit respecter et veiller à la neutralité religieuse dans les services publics ?",
    "Les agents du service public",
    ["Uniquement les enseignants", "Les usagers", "Les élus locaux uniquement"],
    "Tous les agents publics sont tenus à la neutralité religieuse dans l'exercice de leurs fonctions.",
  ),
  annale(
    "an-pv-038",
    "p1-s2",
    2,
    "Une personne déclare ne croire en aucun dieu. On peut dire :",
    "Qu'elle est athée, et c'est son droit",
    ["Qu'elle est hors-la-loi", "Qu'elle doit choisir une religion", "Qu'elle ne peut pas être française"],
    "La liberté de conscience protège aussi le droit de ne pas croire.",
  ),
];
