import type { Qcm } from "../types";
import { annale } from "./helpers";

/**
 * Annales officielles — thème « Système institutionnel et politique »
 * (pages 3-4 du document ministériel, Union européenne comprise).
 */
export const annalesSysteme: Qcm[] = [
  annale(
    "an-si-001",
    "p2-s1",
    3,
    "Comment est désigné le Premier ministre ?",
    "Il est nommé par le président de la République",
    ["Il est élu au suffrage universel direct", "Il est tiré au sort", "Il est désigné par le Sénat"],
    "Le président de la République nomme le Premier ministre (article 8 de la Constitution).",
  ),
  annale(
    "an-si-002",
    "p2-s1",
    3,
    "Qui peut se présenter aux élections présidentielles ?",
    "Tout citoyen français majeur remplissant les conditions, dont 500 parrainages d'élus",
    ["Uniquement les ministres en fonction", "Uniquement les personnes nées en France", "Uniquement les députés"],
    "Il faut être français, électeur, âgé d'au moins 18 ans et réunir 500 parrainages d'élus.",
  ),
  annale(
    "an-si-003",
    "p2-s1",
    3,
    "À qui appartient la souveraineté nationale ?",
    "Au peuple",
    ["Au président de la République", "Au gouvernement", "Aux préfets"],
    "« La souveraineté nationale appartient au peuple qui l'exerce par ses représentants et par la voie du référendum. »",
  ),
  annale(
    "an-si-004",
    "p2-s1",
    3,
    "Qui est élu lors des élections municipales ?",
    "Les conseillers municipaux",
    ["Le préfet", "Les députés", "Les sénateurs"],
    "Les électeurs de la commune élisent les conseillers municipaux, qui élisent ensuite le maire.",
  ),
  annale(
    "an-si-005",
    "p2-s1",
    3,
    "L'inscription sur les listes électorales est :",
    "Indispensable pour pouvoir voter",
    ["Facultative pour voter", "Payante", "Réservée aux plus de 25 ans"],
    "Pour voter, il faut être inscrit sur les listes électorales de sa commune (inscription automatique à 18 ans pour les jeunes recensés).",
  ),
  annale(
    "an-si-006",
    "p2-s1",
    3,
    "Quelle condition est nécessaire pour voter aux élections présidentielles ?",
    "Être français, majeur et inscrit sur les listes électorales",
    ["Payer des impôts en France", "Avoir plus de 21 ans", "Posséder un logement"],
    "Le droit de vote appartient aux citoyens français majeurs inscrits sur les listes électorales et jouissant de leurs droits civiques.",
  ),
  annale(
    "an-si-007",
    "p2-s1",
    3,
    "Quelle condition faut-il remplir pour être candidat aux élections municipales ?",
    "Avoir au moins 18 ans et être électeur ou contribuable de la commune",
    ["Être né dans la commune", "Avoir plus de 30 ans", "Être fonctionnaire"],
    "Tout électeur français ou citoyen de l'UE d'au moins 18 ans, attaché à la commune, peut se présenter.",
  ),
  annale(
    "an-si-008",
    "p2-s1",
    3,
    "Parmi ces autorités, laquelle est élue ?",
    "Le député",
    ["Le préfet", "Le recteur d'académie", "Le commissaire de police"],
    "Le député est élu au suffrage universel direct ; préfet, recteur et commissaire sont nommés.",
  ),
  annale(
    "an-si-009",
    "p2-s2",
    3,
    "Quelles sont les fonctions du maire ?",
    "Diriger l'administration communale et être officier d'état civil",
    ["Voter les lois nationales", "Diriger la police nationale", "Juger les délits"],
    "Le maire gère la commune, célèbre les mariages et représente l'État pour l'état civil.",
  ),
  annale(
    "an-si-010",
    "p2-s1",
    3,
    "Une personne, n'ayant pas d'accès à internet, veut s'inscrire sur les listes électorales pour pouvoir voter aux prochaines élections politiques. Où peut-elle s'inscrire ?",
    "À la mairie de sa commune",
    ["À la préfecture uniquement", "Au commissariat", "Au tribunal"],
    "L'inscription sur les listes électorales se fait en mairie (ou en ligne).",
  ),
  annale(
    "an-si-011",
    "p2-s1",
    3,
    "À quel âge peut-on devenir électeur ?",
    "18 ans",
    ["16 ans", "21 ans", "25 ans"],
    "Le droit de vote s'acquiert à la majorité, fixée à 18 ans.",
  ),
  annale(
    "an-si-012",
    "p2-s1",
    3,
    "En France, est-ce obligatoire de voter ?",
    "Non, voter est un droit, pas une obligation",
    ["Oui, sous peine d'amende", "Oui, pour les fonctionnaires", "Oui, sauf pour les plus de 70 ans"],
    "Le vote est un droit et un devoir civique, mais il n'est pas juridiquement obligatoire.",
  ),
  annale(
    "an-si-013",
    "p2-s1",
    3,
    "A-t-on le droit de ne pas respecter une loi ?",
    "Non, la loi s'impose à tous",
    ["Oui, si on ne l'approuve pas", "Oui, si on est étranger", "Oui, dans sa vie privée"],
    "Nul n'est au-dessus de la loi : elle s'applique à tous, on peut seulement militer pour la changer.",
  ),
  annale(
    "an-si-014",
    "p2-s1",
    3,
    "Comment sont désignés les députés ?",
    "Ils sont élus au suffrage universel direct",
    ["Ils sont nommés par le président", "Ils sont tirés au sort", "Ils sont élus par les maires"],
    "Les députés sont élus pour 5 ans au suffrage universel direct, lors des élections législatives.",
  ),
  annale(
    "an-si-015",
    "p2-s1",
    3,
    "Qui vote les lois ?",
    "Le Parlement (Assemblée nationale et Sénat)",
    ["Le président de la République", "Le Conseil constitutionnel", "Les préfets"],
    "Le pouvoir législatif appartient au Parlement, composé de l'Assemblée nationale et du Sénat.",
  ),
  annale(
    "an-si-016",
    "p2-s1",
    3,
    "La séparation des pouvoirs est un principe fondamental. Quels sont les trois pouvoirs concernés ?",
    "Législatif, exécutif et judiciaire",
    ["National, régional et local", "Civil, militaire et religieux", "Politique, économique et social"],
    "Le pouvoir législatif fait la loi, l'exécutif l'applique, le judiciaire la fait respecter.",
  ),
  annale(
    "an-si-017",
    "p2-s1",
    3,
    "Qu'est-ce que l'État de droit ?",
    "Un État où la loi s'applique à tous, y compris aux pouvoirs publics",
    [
      "Un État dirigé par des juges",
      "Un État sans constitution",
      "Un État où seul le président fait la loi",
    ],
    "Dans un État de droit, chacun — citoyens comme institutions — est soumis au droit.",
  ),
  annale(
    "an-si-018",
    "p2-s2",
    3,
    "Quelles sont les durées du mandat du conseil municipal et du maire ?",
    "6 ans",
    ["5 ans", "4 ans", "7 ans"],
    "Le conseil municipal, et donc le maire qu'il élit, est renouvelé tous les 6 ans.",
  ),
  annale(
    "an-si-019",
    "p2-s1",
    3,
    "Qui est élu lors des élections législatives ?",
    "Les députés",
    ["Les sénateurs", "Les conseillers régionaux", "Le président de la République"],
    "Les législatives désignent les 577 députés de l'Assemblée nationale.",
  ),
  annale(
    "an-si-020",
    "p2-s1",
    3,
    "Quelle est la durée du mandat du Président de la République française ?",
    "5 ans",
    ["7 ans", "4 ans", "6 ans"],
    "Depuis le référendum de 2000, le mandat présidentiel est de 5 ans (quinquennat).",
  ),
  annale(
    "an-si-021",
    "p2-s1",
    3,
    "Quelle est la durée du mandat des députés ?",
    "5 ans",
    ["6 ans", "4 ans", "9 ans"],
    "Les députés sont élus pour 5 ans, sauf dissolution de l'Assemblée nationale.",
  ),
  annale(
    "an-si-022",
    "p2-s1",
    3,
    "Quelle est la durée du mandat des sénateurs ?",
    "6 ans",
    ["5 ans", "7 ans", "3 ans"],
    "Les sénateurs sont élus pour 6 ans au suffrage universel indirect, le Sénat étant renouvelé par moitié tous les 3 ans.",
  ),
  annale(
    "an-si-023",
    "p2-s1",
    3,
    "Qui dirige l'action du gouvernement ?",
    "Le Premier ministre",
    ["Le président du Sénat", "Le ministre de l'Intérieur", "Le Conseil constitutionnel"],
    "Le Premier ministre dirige l'action du gouvernement (article 21 de la Constitution).",
  ),
  annale(
    "an-si-024",
    "p2-s1",
    3,
    "En France, est-ce possible d'adhérer à un parti politique ?",
    "Oui, librement",
    ["Non, c'est réservé aux élus", "Oui, avec l'autorisation du préfet", "Non, les partis sont interdits"],
    "Les partis politiques se forment et exercent leur activité librement (article 4 de la Constitution).",
  ),
  annale(
    "an-si-025",
    "p2-s1",
    3,
    "Qui sanctionne l'auteur d'un vol ?",
    "La justice (un tribunal)",
    ["Le maire", "La victime elle-même", "Le préfet"],
    "Seule l'autorité judiciaire peut juger et sanctionner les infractions : nul ne peut se faire justice soi-même.",
  ),
  annale(
    "an-si-026",
    "p2-s2",
    3,
    "Qui gère les collèges publics ?",
    "Le département",
    ["La commune", "La région", "L'État seul"],
    "Les communes gèrent les écoles, les départements les collèges et les régions les lycées.",
  ),
  annale(
    "an-si-027",
    "p2-s2",
    3,
    "Qui gère les écoles primaires et maternelles publiques ?",
    "La commune",
    ["Le département", "La région", "Le rectorat seul"],
    "La commune construit et entretient les écoles maternelles et élémentaires.",
  ),
  annale(
    "an-si-028",
    "p2-s2",
    3,
    "Comment sont désignés les maires ?",
    "Ils sont élus par le conseil municipal",
    ["Ils sont élus directement par les habitants", "Ils sont nommés par le préfet", "Ils sont tirés au sort"],
    "Après les élections municipales, le conseil municipal élit le maire parmi ses membres.",
  ),
  annale(
    "an-si-029",
    "p2-s2",
    4,
    "Quelle collectivité territoriale est responsable des transports régionaux ?",
    "La région",
    ["La commune", "Le département", "L'État"],
    "La région organise notamment les transports régionaux (TER) et gère les lycées.",
  ),
  annale(
    "an-si-030",
    "p2-s1",
    4,
    "Quelle est l'une des voies possibles pour modifier la Constitution ?",
    "Le référendum",
    ["Un décret du Premier ministre", "Un vote du conseil municipal", "Une décision du Conseil d'État"],
    "La Constitution peut être révisée par référendum ou par le Parlement réuni en Congrès.",
  ),
  annale(
    "an-si-031",
    "p2-s1",
    4,
    "Qui assure l'intérim du président de la République en cas de décès ?",
    "Le président du Sénat",
    ["Le Premier ministre", "Le président de l'Assemblée nationale", "Le ministre de l'Intérieur"],
    "En cas de vacance de la présidence, le président du Sénat assure l'intérim.",
  ),
  annale(
    "an-si-032",
    "p2-s1",
    4,
    "Quel est le rôle du Conseil constitutionnel ?",
    "Vérifier que les lois sont conformes à la Constitution",
    ["Voter les lois", "Diriger le gouvernement", "Juger les crimes"],
    "Le Conseil constitutionnel contrôle la constitutionnalité des lois et veille à la régularité des grandes élections.",
  ),
  annale(
    "an-si-033",
    "p2-s1",
    4,
    "Quelle condition est obligatoire pour se présenter à l'élection présidentielle ?",
    "Avoir la nationalité française",
    ["Être né à Paris", "Avoir été ministre", "Avoir plus de 40 ans"],
    "Le candidat doit être français, électeur, âgé d'au moins 18 ans et parrainé par 500 élus.",
  ),
  annale(
    "an-si-034",
    "p2-s2",
    4,
    "Combien y a-t-il de départements en France ?",
    "101",
    ["95", "83", "110"],
    "La France compte 101 départements, dont 5 d'outre-mer.",
  ),
  annale(
    "an-si-035",
    "p2-s2",
    4,
    "Comment est organisé le découpage administratif de la France ?",
    "En communes, départements et régions",
    ["En provinces et duchés", "En États fédérés", "En cantons uniquement"],
    "Le territoire est organisé en collectivités : communes, départements et régions.",
  ),
  annale(
    "an-si-036",
    "p2-s2",
    4,
    "Qui représente l'État dans un département ?",
    "Le préfet",
    ["Le maire", "Le président du conseil départemental", "Le député"],
    "Le préfet, nommé par le président de la République, représente l'État dans le département.",
  ),
  annale(
    "an-si-037",
    "p2-s1",
    4,
    "Quel est le rôle du Président de la République ?",
    "Chef de l'État, il veille au respect de la Constitution et à l'indépendance nationale",
    ["Il vote les lois", "Il juge les affaires pénales", "Il dirige les communes"],
    "Le président est le chef de l'État, garant des institutions, chef des armées, et il nomme le Premier ministre.",
  ),
  annale(
    "an-si-038",
    "p2-s1",
    4,
    "Quel est le rôle du Premier ministre ?",
    "Diriger l'action du gouvernement et assurer l'exécution des lois",
    ["Présider le Sénat", "Contrôler la constitutionnalité des lois", "Commander la police municipale"],
    "Nommé par le président, le Premier ministre conduit la politique de la Nation avec son gouvernement.",
  ),
  annale(
    "an-si-039",
    "p2-s1",
    4,
    "Quel est le rôle du Défenseur des droits ?",
    "Défendre les citoyens face aux administrations et lutter contre les discriminations",
    ["Défendre la France à l'ONU", "Juger les litiges commerciaux", "Voter le budget de l'État"],
    "Autorité indépendante, le Défenseur des droits protège les droits des usagers et combat les discriminations.",
  ),
  annale(
    "an-si-040",
    "p2-s3",
    4,
    "En quelle année la citoyenneté européenne a-t-elle été créée ?",
    "1992",
    ["1957", "2002", "1981"],
    "La citoyenneté européenne a été instituée par le traité de Maastricht en 1992.",
  ),
  annale(
    "an-si-041",
    "p2-s3",
    4,
    "Quel est le dernier État à avoir intégré l'Union européenne en 2013 ?",
    "La Croatie",
    ["La Serbie", "La Turquie", "La Norvège"],
    "La Croatie est devenue le 28e État membre de l'UE le 1er juillet 2013.",
  ),
  annale(
    "an-si-042",
    "p2-s3",
    4,
    "Qui a composé l'hymne de l'Union européenne ?",
    "Ludwig van Beethoven",
    ["Wolfgang Amadeus Mozart", "Claude Debussy", "Jean-Sébastien Bach"],
    "L'« Ode à la joie », extraite de la 9e symphonie de Beethoven, est l'hymne européen.",
  ),
  annale(
    "an-si-043",
    "p2-s3",
    4,
    "Quand est célébrée la journée de l'Europe ?",
    "Le 9 mai",
    ["Le 14 juillet", "Le 1er janvier", "Le 11 novembre"],
    "Le 9 mai commémore la déclaration Schuman de 1950, acte fondateur de la construction européenne.",
  ),
  annale(
    "an-si-044",
    "p2-s3",
    4,
    "Où est le siège de la Banque centrale européenne ?",
    "À Francfort",
    ["À Bruxelles", "À Paris", "À Genève"],
    "La BCE, qui gère l'euro, siège à Francfort-sur-le-Main, en Allemagne.",
  ),
  annale(
    "an-si-045",
    "p2-s3",
    4,
    "Où est le siège de la Commission européenne ?",
    "À Bruxelles",
    ["À Strasbourg", "À Luxembourg", "À Berlin"],
    "La Commission européenne siège à Bruxelles, en Belgique.",
  ),
  annale(
    "an-si-046",
    "p2-s3",
    4,
    "Qui siège au Parlement européen ?",
    "Les députés européens élus par les citoyens de l'Union",
    ["Les chefs d'État", "Les ambassadeurs", "Les commissaires de police"],
    "Les eurodéputés, élus tous les 5 ans au suffrage universel direct, siègent au Parlement européen.",
  ),
  annale(
    "an-si-047",
    "p2-s3",
    4,
    "Les citoyens de l'Union européenne peuvent-ils voter aux élections locales dans un autre État de l'Union ?",
    "Oui, aux élections municipales et européennes de leur État de résidence",
    ["Non, jamais", "Oui, à toutes les élections", "Seulement après 10 ans de résidence"],
    "La citoyenneté européenne donne le droit de vote aux municipales et aux européennes dans l'État de résidence.",
  ),
  annale(
    "an-si-048",
    "p2-s3",
    4,
    "Combien d'États font partie de l'Union européenne au 1er janvier 2025 ?",
    "27",
    ["25", "28", "30"],
    "Depuis le départ du Royaume-Uni en 2020, l'UE compte 27 États membres.",
  ),
  annale(
    "an-si-049",
    "p2-s3",
    4,
    "En quelle année le traité de Maastricht, qui marque la fondation de l'Union européenne, a-t-il été signé ?",
    "1992",
    ["1957", "1989", "2002"],
    "Signé en 1992, le traité de Maastricht crée l'Union européenne et la citoyenneté européenne.",
  ),
  annale(
    "an-si-050",
    "p2-s3",
    4,
    "Quel traité concerne la construction de l'Union européenne ?",
    "Le traité de Maastricht",
    ["Le traité de Versailles", "Les accords d'Évian", "Le traité de l'Élysée"],
    "Le traité de Maastricht (1992) fonde l'Union européenne ; Versailles (1919) clôt la Première Guerre mondiale.",
  ),
  annale(
    "an-si-051",
    "p2-s3",
    4,
    "Quel État a quitté l'Union européenne en 2020 ?",
    "Le Royaume-Uni",
    ["L'Irlande", "La Suisse", "La Norvège"],
    "Après le référendum de 2016, le Royaume-Uni a quitté l'UE le 31 janvier 2020 (Brexit).",
  ),
  annale(
    "an-si-052",
    "p2-s3",
    4,
    "Quelle est la devise de l'Union européenne ?",
    "« Unie dans la diversité »",
    ["« Liberté, Égalité, Fraternité »", "« L'union fait la force »", "« Paix et prospérité »"],
    "La devise de l'UE est « Unie dans la diversité ».",
  ),
  annale(
    "an-si-053",
    "p2-s3",
    4,
    "Quel est l'hymne de l'Union européenne ?",
    "L'Ode à la joie",
    ["La Marseillaise", "L'Hymne à l'amour", "Le Chant des partisans"],
    "L'hymne européen est l'« Ode à la joie » de Beethoven.",
  ),
  annale(
    "an-si-054",
    "p2-s3",
    4,
    "De quoi est composé le drapeau européen ?",
    "De douze étoiles dorées en cercle sur fond bleu",
    ["De vingt-sept étoiles blanches", "De bandes bleues et jaunes", "D'une colombe sur fond bleu"],
    "Les douze étoiles en cercle symbolisent l'unité et l'harmonie entre les peuples d'Europe.",
  ),
  annale(
    "an-si-055",
    "p2-s3",
    4,
    "Qui élit les députés européens ?",
    "Les citoyens de l'Union européenne, au suffrage universel direct",
    ["Les parlements nationaux", "Les chefs d'État et de gouvernement", "La Commission européenne"],
    "Les eurodéputés sont élus tous les 5 ans par les citoyens de chaque État membre.",
  ),
  annale(
    "an-si-056",
    "p2-s3",
    4,
    "Où est le siège du Parlement européen ?",
    "À Strasbourg",
    ["À Bruxelles uniquement", "À Francfort", "À La Haye"],
    "Le siège officiel du Parlement européen est à Strasbourg, en France.",
  ),
];
