import type { Qcm } from "../types";
import { annale } from "./helpers";

/**
 * Annales officielles — thème « Système institutionnel et politique »
 * (pages 3-4 du document ministériel, Union européenne comprise).
 */
export const annalesSysteme: Qcm[] = [
  annale(
    "an-si-001",
    "p2-s1",
    3,
    "Comment est désigné le Premier ministre ?",
    "Il est nommé par le président de la République",
    [
      "Il est élu par l'Assemblée nationale",
      "Il est élu au suffrage universel direct",
      "Il est désigné par le parti majoritaire",
    ],
    "Le président de la République nomme le Premier ministre (article 8 de la Constitution).",
  ),
  annale(
    "an-si-002",
    "p2-s1",
    3,
    "Qui peut se présenter aux élections présidentielles ?",
    "Tout citoyen français majeur remplissant les conditions, dont 500 parrainages d'élus",
    [
      "Tout citoyen français ayant recueilli 500 000 signatures d'électeurs",
      "Tout citoyen français âgé d'au moins 35 ans",
      "Tout citoyen français ayant déjà exercé un mandat d'élu",
    ],
    "Il faut être français, électeur, âgé d'au moins 18 ans et réunir 500 parrainages d'élus.",
  ),
  annale(
    "an-si-003",
    "p2-s1",
    3,
    "À qui appartient la souveraineté nationale ?",
    "Au peuple",
    ["Au Parlement", "Au président de la République", "À l'État"],
    "« La souveraineté nationale appartient au peuple qui l'exerce par ses représentants et par la voie du référendum. »",
  ),
  annale(
    "an-si-004",
    "p2-s1",
    3,
    "Qui est élu lors des élections municipales ?",
    "Les conseillers municipaux",
    [
      "Le maire, élu directement par les habitants",
      "Les conseillers départementaux",
      "Les conseillers régionaux",
    ],
    "Les électeurs de la commune élisent les conseillers municipaux, qui élisent ensuite le maire.",
  ),
  annale(
    "an-si-005",
    "p2-s1",
    3,
    "L'inscription sur les listes électorales est :",
    "Indispensable pour pouvoir voter",
    [
      "Automatique pour toute personne résidant en France",
      "Facultative si l'on présente sa carte d'identité",
      "Valable pour une seule élection",
    ],
    "Pour voter, il faut être inscrit sur les listes électorales de sa commune (inscription automatique à 18 ans pour les jeunes recensés).",
  ),
  annale(
    "an-si-006",
    "p2-s1",
    3,
    "Quelle condition est nécessaire pour voter aux élections présidentielles ?",
    "Être français, majeur et inscrit sur les listes électorales",
    [
      "Être français, majeur et payer l'impôt sur le revenu",
      "Être majeur et résider en France depuis cinq ans",
      "Être français et avoir au moins 21 ans",
    ],
    "Le droit de vote appartient aux citoyens français majeurs inscrits sur les listes électorales et jouissant de leurs droits civiques.",
  ),
  annale(
    "an-si-007",
    "p2-s1",
    3,
    "Quelle condition faut-il remplir pour être candidat aux élections municipales ?",
    "Avoir au moins 18 ans et être électeur ou contribuable de la commune",
    [
      "Être né dans la commune et y résider",
      "Avoir au moins 23 ans et y habiter depuis 5 ans",
      "Être inscrit dans la commune depuis au moins 10 ans",
    ],
    "Tout électeur français ou citoyen de l'UE d'au moins 18 ans, attaché à la commune, peut se présenter.",
  ),
  annale(
    "an-si-008",
    "p2-s1",
    3,
    "Parmi ces autorités, laquelle est élue ?",
    "Le député",
    ["Le préfet", "Le Premier ministre", "Le recteur d'académie"],
    "Le député est élu au suffrage universel direct ; préfet, recteur et commissaire sont nommés.",
  ),
  annale(
    "an-si-009",
    "p2-s2",
    3,
    "Quelles sont les fonctions du maire ?",
    "Diriger l'administration communale et être officier d'état civil",
    [
      "Diriger la police nationale et la gendarmerie de la commune",
      "Nommer les conseillers municipaux et les adjoints",
      "Juger les litiges entre les habitants de la commune",
    ],
    "Le maire gère la commune, célèbre les mariages et représente l'État pour l'état civil.",
  ),
  annale(
    "an-si-010",
    "p2-s1",
    3,
    "Une personne, n'ayant pas d'accès à internet, veut s'inscrire sur les listes électorales pour pouvoir voter aux prochaines élections politiques. Où peut-elle s'inscrire ?",
    "À la mairie de sa commune",
    ["À la préfecture de son département", "Au tribunal judiciaire", "Au bureau de poste"],
    "L'inscription sur les listes électorales se fait en mairie (ou en ligne).",
  ),
  annale(
    "an-si-011",
    "p2-s1",
    3,
    "À quel âge peut-on devenir électeur ?",
    "18 ans",
    ["16 ans", "21 ans", "17 ans"],
    "Le droit de vote s'acquiert à la majorité, fixée à 18 ans.",
  ),
  annale(
    "an-si-012",
    "p2-s1",
    3,
    "En France, est-ce obligatoire de voter ?",
    "Non, voter est un droit, pas une obligation",
    [
      "Oui, sous peine d'amende",
      "Oui, pour l'élection présidentielle uniquement",
      "Non, sauf pour les élections municipales",
    ],
    "Le vote est un droit et un devoir civique, mais il n'est pas juridiquement obligatoire.",
  ),
  annale(
    "an-si-013",
    "p2-s1",
    3,
    "A-t-on le droit de ne pas respecter une loi ?",
    "Non, la loi s'impose à tous",
    [
      "Oui, si elle est contraire à ses convictions",
      "Oui, tant qu'elle n'a pas été approuvée par référendum",
      "Oui, si l'on n'a pas voté pour les députés qui l'ont adoptée",
    ],
    "Nul n'est au-dessus de la loi : elle s'applique à tous, on peut seulement militer pour la changer.",
  ),
  annale(
    "an-si-014",
    "p2-s1",
    3,
    "Comment sont désignés les députés ?",
    "Ils sont élus au suffrage universel direct",
    [
      "Ils sont élus au suffrage universel indirect",
      "Ils sont élus par les conseillers municipaux",
      "Ils sont nommés par le Premier ministre",
    ],
    "Les députés sont élus pour 5 ans au suffrage universel direct, lors des élections législatives.",
  ),
  annale(
    "an-si-015",
    "p2-s1",
    3,
    "Qui vote les lois ?",
    "Le Parlement (Assemblée nationale et Sénat)",
    ["Le gouvernement", "Le président de la République", "Le Conseil d'État"],
    "Le pouvoir législatif appartient au Parlement, composé de l'Assemblée nationale et du Sénat.",
  ),
  annale(
    "an-si-016",
    "p2-s1",
    3,
    "La séparation des pouvoirs est un principe fondamental. Quels sont les trois pouvoirs concernés ?",
    "Législatif, exécutif et judiciaire",
    [
      "Législatif, exécutif et constitutionnel",
      "Exécutif, judiciaire et médiatique",
      "Législatif, administratif et judiciaire",
    ],
    "Le pouvoir législatif fait la loi, l'exécutif l'applique, le judiciaire la fait respecter.",
  ),
  annale(
    "an-si-017",
    "p2-s1",
    3,
    "Qu'est-ce que l'État de droit ?",
    "Un État où la loi s'applique à tous, y compris aux pouvoirs publics",
    [
      "Un État où le gouvernement peut déroger aux lois",
      "Un État où les juges sont élus par le peuple",
      "Un État dirigé par un président élu",
    ],
    "Dans un État de droit, chacun — citoyens comme institutions — est soumis au droit.",
  ),
  annale(
    "an-si-018",
    "p2-s2",
    3,
    "Quelles sont les durées du mandat du conseil municipal et du maire ?",
    "6 ans",
    ["5 ans", "4 ans", "7 ans"],
    "Le conseil municipal, et donc le maire qu'il élit, est renouvelé tous les 6 ans.",
  ),
  annale(
    "an-si-019",
    "p2-s1",
    3,
    "Qui est élu lors des élections législatives ?",
    "Les députés",
    ["Les sénateurs", "Les conseillers départementaux", "Les députés européens"],
    "Les législatives désignent les 577 députés de l'Assemblée nationale.",
  ),
  annale(
    "an-si-020",
    "p2-s1",
    3,
    "Quelle est la durée du mandat du Président de la République française ?",
    "5 ans",
    ["7 ans", "6 ans", "4 ans"],
    "Depuis le référendum de 2000, le mandat présidentiel est de 5 ans (quinquennat).",
  ),
  annale(
    "an-si-021",
    "p2-s1",
    3,
    "Quelle est la durée du mandat des députés ?",
    "5 ans",
    ["6 ans", "4 ans", "7 ans"],
    "Les députés sont élus pour 5 ans, sauf dissolution de l'Assemblée nationale.",
  ),
  annale(
    "an-si-022",
    "p2-s1",
    3,
    "Quelle est la durée du mandat des sénateurs ?",
    "6 ans",
    ["9 ans", "5 ans", "7 ans"],
    "Les sénateurs sont élus pour 6 ans au suffrage universel indirect, le Sénat étant renouvelé par moitié tous les 3 ans.",
  ),
  annale(
    "an-si-023",
    "p2-s1",
    3,
    "Qui dirige l'action du gouvernement ?",
    "Le Premier ministre",
    [
      "Le président de l'Assemblée nationale",
      "Le ministre de l'Intérieur",
      "Le président du Sénat",
    ],
    "Le Premier ministre dirige l'action du gouvernement (article 21 de la Constitution).",
  ),
  annale(
    "an-si-024",
    "p2-s1",
    3,
    "En France, est-ce possible d'adhérer à un parti politique ?",
    "Oui, librement",
    [
      "Oui, mais seulement à partir de 21 ans",
      "Oui, après déclaration à la mairie",
      "Non, c'est réservé aux élus",
    ],
    "Les partis politiques se forment et exercent leur activité librement (article 4 de la Constitution).",
  ),
  annale(
    "an-si-025",
    "p2-s1",
    3,
    "Qui sanctionne l'auteur d'un vol ?",
    "La justice (un tribunal)",
    ["La police", "Le maire de la commune", "Le préfet"],
    "Seule l'autorité judiciaire peut juger et sanctionner les infractions : nul ne peut se faire justice soi-même.",
  ),
  annale(
    "an-si-026",
    "p2-s2",
    3,
    "Qui gère les collèges publics ?",
    "Le département",
    ["La commune", "La région", "Le rectorat"],
    "Les communes gèrent les écoles, les départements les collèges et les régions les lycées.",
  ),
  annale(
    "an-si-027",
    "p2-s2",
    3,
    "Qui gère les écoles primaires et maternelles publiques ?",
    "La commune",
    ["Le département", "La région", "La préfecture"],
    "La commune construit et entretient les écoles maternelles et élémentaires.",
  ),
  annale(
    "an-si-028",
    "p2-s2",
    3,
    "Comment sont désignés les maires ?",
    "Ils sont élus par le conseil municipal",
    [
      "Ils sont élus directement par les habitants",
      "Ils sont nommés par le préfet",
      "Ils sont élus par les conseillers départementaux",
    ],
    "Après les élections municipales, le conseil municipal élit le maire parmi ses membres.",
  ),
  annale(
    "an-si-029",
    "p2-s2",
    4,
    "Quelle collectivité territoriale est responsable des transports régionaux ?",
    "La région",
    ["Le département", "La commune", "L'intercommunalité"],
    "La région organise notamment les transports régionaux (TER) et gère les lycées.",
  ),
  annale(
    "an-si-030",
    "p2-s1",
    4,
    "Quelle est l'une des voies possibles pour modifier la Constitution ?",
    "Le référendum",
    [
      "Une loi ordinaire votée par l'Assemblée nationale",
      "Un décret du président de la République",
      "Une décision du Conseil constitutionnel",
    ],
    "La Constitution peut être révisée par référendum ou par le Parlement réuni en Congrès.",
  ),
  annale(
    "an-si-031",
    "p2-s1",
    4,
    "Qui assure l'intérim du président de la République en cas de décès ?",
    "Le président du Sénat",
    [
      "Le Premier ministre",
      "Le président de l'Assemblée nationale",
      "Le président du Conseil constitutionnel",
    ],
    "En cas de vacance de la présidence, le président du Sénat assure l'intérim.",
  ),
  annale(
    "an-si-032",
    "p2-s1",
    4,
    "Quel est le rôle du Conseil constitutionnel ?",
    "Vérifier que les lois sont conformes à la Constitution",
    [
      "Contrôler l'action du gouvernement",
      "Juger les litiges entre l'administration et les citoyens",
      "Conseiller le gouvernement sur ses projets de loi",
    ],
    "Le Conseil constitutionnel contrôle la constitutionnalité des lois et veille à la régularité des grandes élections.",
  ),
  annale(
    "an-si-033",
    "p2-s1",
    4,
    "Quelle condition est obligatoire pour se présenter à l'élection présidentielle ?",
    "Avoir la nationalité française",
    [
      "Avoir au moins 35 ans",
      "Être membre d'un parti politique",
      "Avoir déjà exercé un mandat électif",
    ],
    "Le candidat doit être français, électeur, âgé d'au moins 18 ans et parrainé par 500 élus.",
  ),
  annale(
    "an-si-034",
    "p2-s2",
    4,
    "Combien y a-t-il de départements en France ?",
    "101",
    ["96", "100", "95"],
    "La France compte 101 départements, dont 5 d'outre-mer.",
  ),
  annale(
    "an-si-035",
    "p2-s2",
    4,
    "Comment est organisé le découpage administratif de la France ?",
    "En communes, départements et régions",
    [
      "En communes, cantons et provinces",
      "En régions et États fédérés",
      "En départements et provinces",
    ],
    "Le territoire est organisé en collectivités : communes, départements et régions.",
  ),
  annale(
    "an-si-036",
    "p2-s2",
    4,
    "Qui représente l'État dans un département ?",
    "Le préfet",
    [
      "Le président du conseil départemental",
      "Le maire du chef-lieu",
      "Le sénateur du département",
    ],
    "Le préfet, nommé par le président de la République, représente l'État dans le département.",
  ),
  annale(
    "an-si-037",
    "p2-s1",
    4,
    "Quel est le rôle du Président de la République ?",
    "Chef de l'État, il veille au respect de la Constitution et à l'indépendance nationale",
    [
      "Chef du gouvernement, il dirige l'action des ministres et l'administration",
      "Chef du Parlement, il vote les lois et contrôle le gouvernement",
      "Chef de la justice, il nomme et révoque librement les juges",
    ],
    "Le président est le chef de l'État, garant des institutions, chef des armées, et il nomme le Premier ministre.",
  ),
  annale(
    "an-si-038",
    "p2-s1",
    4,
    "Quel est le rôle du Premier ministre ?",
    "Diriger l'action du gouvernement et assurer l'exécution des lois",
    [
      "Présider le Conseil des ministres et promulguer les lois",
      "Présider l'Assemblée nationale et fixer son ordre du jour",
      "Commander les armées et négocier les traités",
    ],
    "Nommé par le président, le Premier ministre conduit la politique de la Nation avec son gouvernement.",
  ),
  annale(
    "an-si-039",
    "p2-s1",
    4,
    "Quel est le rôle du Défenseur des droits ?",
    "Défendre les citoyens face aux administrations et lutter contre les discriminations",
    [
      "Défendre les accusés devant les tribunaux",
      "Contrôler la conformité des lois à la Constitution",
      "Représenter la France devant les cours européennes",
    ],
    "Autorité indépendante, le Défenseur des droits protège les droits des usagers et combat les discriminations.",
  ),
  annale(
    "an-si-040",
    "p2-s3",
    4,
    "En quelle année la citoyenneté européenne a-t-elle été créée ?",
    "1992",
    ["1957", "1979", "1986"],
    "La citoyenneté européenne a été instituée par le traité de Maastricht en 1992.",
  ),
  annale(
    "an-si-041",
    "p2-s3",
    4,
    "Quel est le dernier État à avoir intégré l'Union européenne en 2013 ?",
    "La Croatie",
    ["La Bulgarie", "La Slovénie", "La Serbie"],
    "La Croatie est devenue le 28e État membre de l'UE le 1er juillet 2013.",
  ),
  annale(
    "an-si-042",
    "p2-s3",
    4,
    "Qui a composé l'hymne de l'Union européenne ?",
    "Ludwig van Beethoven",
    ["Wolfgang Amadeus Mozart", "Joseph Haydn", "Franz Schubert"],
    "L'« Ode à la joie », extraite de la 9e symphonie de Beethoven, est l'hymne européen.",
  ),
  annale(
    "an-si-043",
    "p2-s3",
    4,
    "Quand est célébrée la journée de l'Europe ?",
    "Le 9 mai",
    ["Le 8 mai", "Le 1er mai", "Le 25 mars"],
    "Le 9 mai commémore la déclaration Schuman de 1950, acte fondateur de la construction européenne.",
  ),
  annale(
    "an-si-044",
    "p2-s3",
    4,
    "Où est le siège de la Banque centrale européenne ?",
    "À Francfort",
    ["À Bruxelles", "À Luxembourg", "À Strasbourg"],
    "La BCE, qui gère l'euro, siège à Francfort-sur-le-Main, en Allemagne.",
  ),
  annale(
    "an-si-045",
    "p2-s3",
    4,
    "Où est le siège de la Commission européenne ?",
    "À Bruxelles",
    ["À Strasbourg", "À Luxembourg", "À La Haye"],
    "La Commission européenne siège à Bruxelles, en Belgique.",
  ),
  annale(
    "an-si-046",
    "p2-s3",
    4,
    "Qui siège au Parlement européen ?",
    "Les députés européens élus par les citoyens de l'Union",
    [
      "Les ministres des États membres",
      "Les commissaires européens",
      "Des députés désignés par les parlements nationaux",
    ],
    "Les eurodéputés, élus tous les 5 ans au suffrage universel direct, siègent au Parlement européen.",
  ),
  annale(
    "an-si-047",
    "p2-s3",
    4,
    "Les citoyens de l'Union européenne peuvent-ils voter aux élections locales dans un autre État de l'Union ?",
    "Oui, aux élections municipales et européennes de leur État de résidence",
    [
      "Oui, à toutes les élections, y compris nationales",
      "Non, ils votent uniquement dans leur pays d'origine",
      "Oui, mais uniquement aux élections européennes",
    ],
    "La citoyenneté européenne donne le droit de vote aux municipales et aux européennes dans l'État de résidence.",
  ),
  annale(
    "an-si-048",
    "p2-s3",
    4,
    "Combien d'États font partie de l'Union européenne au 1er janvier 2025 ?",
    "27",
    ["28", "25", "26"],
    "Depuis le départ du Royaume-Uni en 2020, l'UE compte 27 États membres.",
  ),
  annale(
    "an-si-049",
    "p2-s3",
    4,
    "En quelle année le traité de Maastricht, qui marque la fondation de l'Union européenne, a-t-il été signé ?",
    "1992",
    ["1957", "1986", "1999"],
    "Signé en 1992, le traité de Maastricht crée l'Union européenne et la citoyenneté européenne.",
  ),
  annale(
    "an-si-050",
    "p2-s3",
    4,
    "Quel traité concerne la construction de l'Union européenne ?",
    "Le traité de Maastricht",
    ["Le traité de Versailles", "Le traité de l'Élysée", "Le traité de l'Atlantique Nord"],
    "Le traité de Maastricht (1992) fonde l'Union européenne ; Versailles (1919) clôt la Première Guerre mondiale.",
  ),
  annale(
    "an-si-051",
    "p2-s3",
    4,
    "Quel État a quitté l'Union européenne en 2020 ?",
    "Le Royaume-Uni",
    ["La Suisse", "Le Danemark", "La Norvège"],
    "Après le référendum de 2016, le Royaume-Uni a quitté l'UE le 31 janvier 2020 (Brexit).",
  ),
  annale(
    "an-si-052",
    "p2-s3",
    4,
    "Quelle est la devise de l'Union européenne ?",
    "« Unie dans la diversité »",
    ["« Unie dans la paix »", "« L'union fait la force »", "« Liberté, Égalité, Fraternité »"],
    "La devise de l'UE est « Unie dans la diversité ».",
  ),
  annale(
    "an-si-053",
    "p2-s3",
    4,
    "Quel est l'hymne de l'Union européenne ?",
    "L'Ode à la joie",
    ["Le Beau Danube bleu", "Le Boléro", "L'Hymne à la paix"],
    "L'hymne européen est l'« Ode à la joie » de Beethoven.",
  ),
  annale(
    "an-si-054",
    "p2-s3",
    4,
    "De quoi est composé le drapeau européen ?",
    "De douze étoiles dorées en cercle sur fond bleu",
    [
      "De vingt-sept étoiles dorées en cercle sur fond bleu",
      "De douze étoiles blanches en cercle sur fond bleu",
      "De douze étoiles dorées en carré sur fond blanc",
    ],
    "Les douze étoiles en cercle symbolisent l'unité et l'harmonie entre les peuples d'Europe.",
  ),
  annale(
    "an-si-055",
    "p2-s3",
    4,
    "Qui élit les députés européens ?",
    "Les citoyens de l'Union européenne, au suffrage universel direct",
    [
      "Les parlements nationaux de chaque État membre",
      "Les chefs d'État et de gouvernement",
      "Les citoyens de l'Union, au suffrage universel indirect",
    ],
    "Les eurodéputés sont élus tous les 5 ans par les citoyens de chaque État membre.",
  ),
  annale(
    "an-si-056",
    "p2-s3",
    4,
    "Où est le siège du Parlement européen ?",
    "À Strasbourg",
    ["À Bruxelles", "À Francfort", "À La Haye"],
    "Le siège officiel du Parlement européen est à Strasbourg, en France.",
  ),
];
