import type { Qcm } from "../types";
import { annale } from "./helpers";

/**
 * Annales officielles — thème « Vivre dans la société française »
 * (pages 10-11 du document ministériel).
 */
export const annalesVivre: Qcm[] = [
  annale(
    "an-vs-001",
    "p5-s1",
    10,
    "Où faut-il déclarer la naissance d'un enfant ?",
    "À la mairie du lieu de naissance",
    ["À la préfecture", "Au tribunal", "À la caisse d'allocations familiales"],
    "La naissance est déclarée au service d'état civil de la mairie du lieu de naissance.",
  ),
  annale(
    "an-vs-002",
    "p5-s1",
    10,
    "Quelle action peut réaliser le locataire d'un logement sans l'autorisation du propriétaire ?",
    "Repeindre les murs de son logement",
    ["Abattre une cloison", "Changer les fenêtres", "Transformer le logement en commerce"],
    "Le locataire peut faire des aménagements simples (peinture, décoration) ; les transformations lourdes exigent l'accord du propriétaire.",
  ),
  annale(
    "an-vs-003",
    "p5-s3",
    10,
    "Quel mariage est reconnu légalement ?",
    "Le mariage civil célébré en mairie",
    ["Le mariage religieux seul", "Le mariage coutumier", "Les fiançailles"],
    "Seul le mariage civil a une valeur légale ; la cérémonie religieuse ne peut avoir lieu qu'après.",
  ),
  annale(
    "an-vs-004",
    "p5-s1",
    10,
    "Le stationnement sur une place réservée aux personnes handicapées :",
    "Est interdit et puni d'une amende",
    ["Est toléré 10 minutes", "Est autorisé la nuit", "Est autorisé le dimanche"],
    "Stationner sans carte sur une place réservée est une infraction passible d'une amende de 135 €.",
  ),
  annale(
    "an-vs-005",
    "p5-s1",
    10,
    "Si une machine à laver est cassée, il est possible de :",
    "La faire réparer ou la déposer en déchetterie pour recyclage",
    ["La jeter sur le trottoir", "La brûler dans son jardin", "L'abandonner dans la nature"],
    "Les encombrants et appareils électriques se réparent, se donnent ou se recyclent — jamais dans la nature.",
  ),
  annale(
    "an-vs-006",
    "p5-s3",
    10,
    "Dans quel cas faut-il déclarer son enfant au service d'état civil ?",
    "Dans tous les cas, pour toute naissance",
    ["Seulement si les parents sont mariés", "Seulement pour le premier enfant", "Seulement si l'enfant est né en France"],
    "Toute naissance doit être déclarée à l'état civil : c'est ce qui établit l'existence juridique de l'enfant.",
  ),
  annale(
    "an-vs-007",
    "p5-s3",
    10,
    "Quand faut-il déclarer son enfant au service d'état civil ?",
    "Dans les 5 jours suivant la naissance",
    ["Dans le mois suivant la naissance", "Avant ses 1 an", "Le jour même uniquement"],
    "La déclaration de naissance doit être faite dans les 5 jours à la mairie du lieu de naissance.",
  ),
  annale(
    "an-vs-008",
    "p5-s1",
    10,
    "Quel numéro d'urgence permet d'appeler la police ?",
    "Le 17",
    ["Le 15", "Le 18", "Le 115"],
    "Le 17 joint la police, le 15 le SAMU, le 18 les pompiers, le 112 est le numéro européen.",
  ),
  annale(
    "an-vs-009",
    "p5-s1",
    10,
    "Quel numéro d'urgence permet d'appeler le SAMU ?",
    "Le 15",
    ["Le 17", "Le 18", "Le 3615"],
    "Le 15 est le numéro du SAMU (urgences médicales).",
  ),
  annale(
    "an-vs-010",
    "p5-s1",
    10,
    "Auprès de quelle institution les parents peuvent inscrire leurs enfants à l'école publique ?",
    "La mairie",
    ["La préfecture", "Le rectorat", "La caisse d'allocations familiales"],
    "L'inscription à l'école maternelle et élémentaire publique se fait à la mairie de la commune.",
  ),
  annale(
    "an-vs-011",
    "p5-s3",
    10,
    "En cas de divorce, qui exerce l'autorité parentale ?",
    "Les deux parents, en commun",
    ["La mère uniquement", "Le père uniquement", "Le juge"],
    "Sauf décision contraire du juge, l'autorité parentale reste exercée conjointement après le divorce.",
  ),
  annale(
    "an-vs-012",
    "p5-s1",
    10,
    "Quelle aide permet aux personnes qui ont des difficultés financières d'avoir un avocat ?",
    "L'aide juridictionnelle",
    ["Le RSA", "L'allocation logement", "La prime d'activité"],
    "L'aide juridictionnelle prend en charge tout ou partie des frais de justice et d'avocat.",
  ),
  annale(
    "an-vs-013",
    "p5-s3",
    10,
    "Qui peut demander le divorce de personnes mariées ?",
    "Chacun des deux époux",
    ["Seulement le mari", "Seulement la femme", "Les beaux-parents"],
    "Le divorce peut être demandé par l'un ou l'autre des époux, ou par les deux ensemble.",
  ),
  annale(
    "an-vs-014",
    "p5-s1",
    10,
    "Auprès de quel organisme faut-il demander le remboursement des frais de santé ?",
    "L'Assurance maladie",
    ["La caisse d'allocations familiales", "France Travail", "La mairie"],
    "L'Assurance maladie (CPAM) rembourse les frais de santé, en partie complétés par une mutuelle.",
  ),
  annale(
    "an-vs-015",
    "p5-s1",
    10,
    "La contraception :",
    "Est libre et peut être remboursée par l'Assurance maladie",
    ["Est interdite", "Nécessite l'accord du mari", "Est réservée aux personnes mariées"],
    "La contraception est un droit ; elle est gratuite pour les moins de 26 ans.",
  ),
  annale(
    "an-vs-016",
    "p5-s1",
    10,
    "Qu'est-ce que le principe de confidentialité dans le domaine de la santé ?",
    "Les soignants ne divulguent pas les informations médicales des patients",
    [
      "Les hôpitaux sont fermés au public",
      "Les patients ne connaissent pas leur diagnostic",
      "Les médicaments sont vendus sans ordonnance",
    ],
    "Le secret médical protège toutes les informations de santé du patient.",
  ),
  annale(
    "an-vs-017",
    "p5-s1",
    10,
    "À quoi sert la carte Vitale ?",
    "À justifier de ses droits à l'Assurance maladie et être remboursé",
    ["À payer chez le médecin", "À prouver son identité", "À voter"],
    "La carte Vitale atteste des droits à l'Assurance maladie et permet le remboursement automatique des soins.",
  ),
  annale(
    "an-vs-018",
    "p5-s1",
    10,
    "À quoi sert une mutuelle santé ?",
    "À compléter les remboursements de l'Assurance maladie",
    ["À remplacer le médecin traitant", "À payer ses impôts", "À obtenir la carte Vitale"],
    "La complémentaire santé rembourse tout ou partie des frais non couverts par la Sécurité sociale.",
  ),
  annale(
    "an-vs-019",
    "p5-s1",
    10,
    "Qu'est-ce que le tiers payant ?",
    "Ne pas avancer les frais médicaux",
    ["Payer en trois fois", "Une taxe sur les médicaments", "Un impôt sur la santé"],
    "Avec le tiers payant, l'Assurance maladie et la mutuelle paient directement le professionnel de santé.",
  ),
  annale(
    "an-vs-020",
    "p5-s1",
    10,
    "L'inscription à l'Assurance maladie est :",
    "Obligatoire pour toute personne travaillant ou résidant en France de façon stable",
    ["Facultative", "Réservée aux salariés", "Payante à l'inscription"],
    "Toute personne résidant ou travaillant en France de manière stable et régulière relève de l'Assurance maladie.",
  ),
  annale(
    "an-vs-021",
    "p5-s1",
    10,
    "L'avortement est-il possible en France ?",
    "Oui, l'IVG est un droit garanti par la loi",
    ["Non, il est interdit", "Oui, avec l'accord du conjoint", "Oui, uniquement à l'étranger"],
    "L'IVG est légale depuis la loi Veil de 1975 ; sa liberté est inscrite dans la Constitution depuis 2024.",
  ),
  annale(
    "an-vs-022",
    "p5-s2",
    10,
    "Travailler sans être déclaré est :",
    "Interdit : c'est du travail dissimulé, sanctionné par la loi",
    ["Autorisé pour les petits boulots", "Autorisé moins de 10 heures par semaine", "Un choix personnel"],
    "Le travail non déclaré prive de protection sociale et expose employeur et salarié à des sanctions.",
  ),
  annale(
    "an-vs-023",
    "p5-s2",
    10,
    "Qu'est-ce que le SMIC ?",
    "Le salaire minimum légal en France",
    ["Un impôt sur les salaires", "Une aide au logement", "Un contrat de travail"],
    "Le SMIC (salaire minimum interprofessionnel de croissance) est le salaire horaire minimum légal.",
  ),
  annale(
    "an-vs-024",
    "p5-s2",
    10,
    "Quelle est la première démarche à réaliser pour chercher un emploi ?",
    "S'inscrire à France Travail",
    ["Aller à la préfecture", "S'inscrire à la mairie", "Contacter son député"],
    "France Travail (ex-Pôle emploi) accompagne la recherche d'emploi et verse les allocations chômage.",
  ),
  annale(
    "an-vs-025",
    "p5-s2",
    10,
    "Quelle est la durée légale du temps de travail par semaine ?",
    "35 heures",
    ["39 heures", "40 heures", "48 heures"],
    "La durée légale du travail à temps complet est de 35 heures par semaine.",
  ),
  annale(
    "an-vs-026",
    "p5-s3",
    10,
    "Qui peut demander un congé parental d'éducation ?",
    "Chacun des deux parents",
    ["La mère uniquement", "Le père uniquement", "Les grands-parents"],
    "Le congé parental est ouvert au père comme à la mère, après la naissance ou l'adoption.",
  ),
  annale(
    "an-vs-027",
    "p5-s2",
    10,
    "Une personne étrangère, en situation régulière, peut créer son entreprise :",
    "Oui, elle en a le droit",
    ["Non, jamais", "Oui, après 10 ans en France", "Oui, seulement avec un associé français"],
    "Toute personne en situation régulière peut créer une entreprise en France.",
  ),
  annale(
    "an-vs-028",
    "p5-s2",
    10,
    "Une femme peut-elle créer son entreprise ?",
    "Oui, librement, sans aucune autorisation",
    ["Non", "Oui, avec l'accord de son mari", "Oui, uniquement dans certains secteurs"],
    "Hommes et femmes sont égaux en droits : une femme entreprend librement.",
  ),
  annale(
    "an-vs-029",
    "p5-s2",
    10,
    "Quels sont les textes qui définissent les règles au travail ?",
    "Le Code du travail et les conventions collectives",
    ["Le Code civil uniquement", "Le règlement municipal", "La Constitution uniquement"],
    "Le Code du travail et les conventions collectives fixent les droits et devoirs au travail.",
  ),
  annale(
    "an-vs-030",
    "p5-s2",
    10,
    "Quelles sont les affaires traitées par le conseil de prud'hommes ?",
    "Les litiges entre salariés et employeurs",
    ["Les divorces", "Les crimes", "Les litiges entre voisins"],
    "Les prud'hommes règlent les conflits individuels liés au contrat de travail.",
  ),
  annale(
    "an-vs-031",
    "p5-s2",
    11,
    "Qui a le droit de se syndiquer ?",
    "Tout salarié, quelle que soit sa nationalité",
    ["Uniquement les cadres", "Uniquement les Français", "Uniquement les fonctionnaires"],
    "La liberté syndicale est garantie à tous les travailleurs.",
  ),
  annale(
    "an-vs-032",
    "p5-s2",
    11,
    "Est-il possible de licencier une femme enceinte ou en congé maternité, en raison de sa grossesse ?",
    "Non, c'est interdit par la loi",
    ["Oui, librement", "Oui, avec un préavis", "Oui, si l'entreprise est petite"],
    "Le licenciement lié à la grossesse ou à la maternité est une discrimination interdite.",
  ),
  annale(
    "an-vs-033",
    "p5-s3",
    11,
    "L'instruction des enfants est obligatoire de :",
    "3 à 16 ans",
    ["6 à 14 ans", "5 à 18 ans", "7 à 16 ans"],
    "Depuis 2019, l'instruction est obligatoire de 3 à 16 ans, puis formation obligatoire jusqu'à 18 ans.",
  ),
  annale(
    "an-vs-034",
    "p5-s3",
    11,
    "Des parents ne respectent pas l'obligation d'instruction pour leurs enfants. Quelle sanction maximale risquent-ils ?",
    "Des sanctions pénales : amende et peine de prison",
    ["Un simple avertissement", "Aucune sanction", "La perte de leur logement"],
    "Le non-respect de l'obligation d'instruction est un délit passible d'amende et d'emprisonnement.",
  ),
  annale(
    "an-vs-035",
    "p5-s3",
    11,
    "Quelle est la définition de l'autorité parentale ?",
    "L'ensemble des droits et devoirs des parents pour protéger l'enfant et assurer son éducation",
    [
      "Le droit de punir physiquement ses enfants",
      "Le pouvoir de l'État sur les familles",
      "Le droit des enfants de choisir leurs parents",
    ],
    "L'autorité parentale vise l'intérêt de l'enfant : le protéger, l'entretenir et l'éduquer.",
  ),
  annale(
    "an-vs-036",
    "p5-s3",
    11,
    "Quel motif d'absence est accepté par l'école ?",
    "La maladie de l'enfant",
    ["Les soldes", "Un match de football", "La grasse matinée"],
    "Seuls des motifs légitimes (maladie, réunion de famille exceptionnelle…) justifient une absence scolaire.",
  ),
  annale(
    "an-vs-037",
    "p5-s3",
    11,
    "Jusqu'à quel âge l'école est-elle obligatoire ?",
    "16 ans",
    ["14 ans", "18 ans", "21 ans"],
    "L'instruction est obligatoire jusqu'à 16 ans ; une formation est ensuite obligatoire jusqu'à 18 ans.",
  ),
  annale(
    "an-vs-038",
    "p5-s3",
    11,
    "À quel âge commence l'instruction obligatoire des enfants ?",
    "3 ans",
    ["6 ans", "5 ans", "7 ans"],
    "Depuis la rentrée 2019, l'instruction est obligatoire dès 3 ans.",
  ),
  annale(
    "an-vs-039",
    "p5-s3",
    11,
    "Comment s'appellent les établissements scolaires que les élèves intègrent après l'école élémentaire ?",
    "Les collèges",
    ["Les lycées", "Les universités", "Les crèches"],
    "Après l'école élémentaire, les élèves entrent au collège (de la 6e à la 3e).",
  ),
  annale(
    "an-vs-040",
    "p5-s3",
    11,
    "En tant que parent d'élève, il est possible de :",
    "Participer aux élections des représentants de parents d'élèves",
    ["Choisir les enseignants de son enfant", "Modifier les programmes scolaires", "Noter les professeurs"],
    "Les parents participent à la vie de l'école, notamment via leurs représentants élus.",
  ),
  annale(
    "an-vs-041",
    "p5-s3",
    11,
    "Quelle instruction est prévue pour les enfants qui ne parlent pas français ?",
    "Un accueil en classe spécifique avec un enseignement renforcé du français",
    ["Aucune scolarisation", "Un retour dans leur pays d'origine", "Une école séparée payante"],
    "Les élèves allophones sont scolarisés et bénéficient d'unités pédagogiques dédiées (UPE2A) pour apprendre le français.",
  ),
  annale(
    "an-vs-042",
    "p5-s3",
    11,
    "S'agissant de l'accueil des enfants en situation de handicap à l'école, laquelle des propositions est vraie ?",
    "Ils ont le droit d'être scolarisés, avec un accompagnement adapté",
    ["Ils ne peuvent pas aller à l'école", "Ils doivent payer leur scolarité", "Ils sont scolarisés uniquement à domicile"],
    "L'école inclusive garantit la scolarisation des élèves en situation de handicap, avec des accompagnants (AESH).",
  ),
  annale(
    "an-vs-043",
    "p5-s3",
    11,
    "Depuis le 1er juillet 2021, quelle est la durée du congé paternité ?",
    "25 jours",
    ["3 jours", "11 jours", "6 mois"],
    "Le congé de paternité est de 25 jours calendaires (32 en cas de naissances multiples), en plus des 3 jours de congé de naissance.",
  ),
  annale(
    "an-vs-044",
    "p5-s3",
    11,
    "Est-ce possible de punir physiquement ses enfants ?",
    "Non, les violences éducatives ordinaires sont interdites",
    ["Oui, c'est un droit des parents", "Oui, jusqu'à 10 ans", "Oui, si c'est léger"],
    "Depuis la loi de 2019, l'autorité parentale s'exerce sans violences physiques ni psychologiques.",
  ),
];
